### ISSUE TITLE
Restarter / Autoshut down failing

### ISSUE THREAD

**Issue by BigBearEvo** [jackbayliss/Mission-Chief-Bot#1]
When using the restarter module, i have the config set to auto shut down after 12 hrs ish, this allows the bot to refresh, claim daily's etc, but it is not not doing this at all anymore. t
it's almost like its ignoring it totally from the config

**Comment by jackbayliss** [comment]
Due to threading etc it's been changed slightly; that being said it may of changed at which method it restarts at. Let me play with it and get back to you :)

**Comment by jackbayliss** [comment]
Can confirm there was an issue with it blocking when exiting, it's been fixed and will be in with the next patch 😃

**Comment by jackbayliss** [comment]
Fixed in the next patch :)
