### ISSUE TITLE
Json.decoder error

### ISSUE THREAD

**Issue by mlande5** [jackbayliss/Mission-Chief-Bot#107]
continuously seeing <class 'json.decoder.JSONDecodeError'> <frozen MissionChiefBot> 350. 

I'm currently running on version 0.5 and have restarted the program. But continue to see the message after UPDATE Checking vehicle state for region...

Thank you 

Mike

**Comment by NotoriousBims** [comment]
Are you using old files and it autoupdated? 

If so, please download the new copy and start off fresh. Some files were changed and seem to be causing issues.
