### ISSUE TITLE
Wrong number of needed units when some on scene.

### ISSUE THREAD

**Issue by sliwma** [jackbayliss/Mission-Chief-Bot#11]
date&time: Generating Missions...
date&time: Building Vehicles...
date&time: X missions found
date&time: Mission Fire in Hospital was not despatched
date&time: qty we have : 27 - qty required 45
And there're about 24 on scene.

Happens both when dispatched manualy and when mission escalates.

**Comment by jackbayliss** [comment]
This (hopefully) will be in a later patch, the current version doesn't account for whats there, it just reads the new requirements of the escalated mission and tries to despatch as if nothing was there.  Thanks for using the bot :) 👍

**Comment by jackbayliss** [comment]
@sliwma 
This is implemented in the newest version - 0.0.9 onwards.

Any vehicles on scene or on route are deducted from the qty we require, thus- only sending what we need.
