### ISSUE TITLE
Kubernetes issue waiting for Checking links & missing...

### ISSUE THREAD

**Issue by kaijehenstra** [jackbayliss/Mission-Chief-Bot#11]
Image

The container gets stuck on [UPDATE] Checking links & missing... in kubernetes (Digital Ocean) but not in docker.

**Comment by jackbayliss** [comment]
@kaijehenstra  Hello! Sorry to hear you're having issues. I've confirmed it working on Docker

I will have to run a test on Kubernetes, I can only presume it's some kind of dir issue.  Also, remove the image! It has your username in.

**Comment by kaijehenstra** [comment]
Image has been made private

**Comment by kaijehenstra** [comment]
root@missionchief-nl-86566f4b97-bbftj:/Mission-Chief-Bot# pip3 install discord_webhook
Requirement already satisfied: discord_webhook in /usr/local/lib/python3.8/dist-packages (0.14.0)
Requirement already satisfied: requests>=2.19.1 in /usr/local/lib/python3.8/dist-packages (from discord_webhook) (2.23.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.19.1->discord_webhook) (1.25.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests>=2.19.1->discord_webhook) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.19.1->discord_webhook) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.19.1->discord_webhook) (2019.11.28)

root@missionchief-nl-86566f4b97-bbftj:/Mission-Chief-Bot# python3 MissionChiefBot.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                     
    • ▌ ▄ ·. ▪  .▄▄ · .▄▄ · ▪         ▐ ▄      ▄▄·  ▄ .▄▪  ▄▄▄ .·▄▄▄    ▄▄▄▄·       ▄▄▄▄▄
    ·██ ▐███▪██ ▐█ ▀. ▐█ ▀. ██ ▪     •█▌▐█    ▐█ ▌▪██▪▐███ ▀▄.▀·▐▄▄·    ▐█ ▀█▪▪     •██  
    ▐█ ▌▐▌▐█·▐█·▄▀▀▀█▄▄▀▀▀█▄▐█· ▄█▀▄ ▐█▐▐▌    ██ ▄▄██▀▐█▐█·▐▀▀▪▄██▪     ▐█▀▀█▄ ▄█▀▄  ▐█.▪
    ██ ██▌▐█▌▐█▌▐█▄▪▐█▐█▄▪▐█▐█▌▐█▌.▐▌██▐█▌    ▐███▌██▌▐▀▐█▌▐█▄▄▌██▌.    ██▄▪▐█▐█▌.▐▌ ▐█▌·
    ▀▀  █▪▀▀▀▀▀▀ ▀▀▀▀  ▀▀▀▀ ▀▀▀ ▀█▄▀▪▀▀ █▪    ·▀▀▀ ▀▀▀ ·▀▀▀ ▀▀▀ ▀▀▀     ·▀▀▀▀  ▀█▄▀▪ ▀▀▀ 
                       
  Version 0.1.9
  Created, by Jack Bayliss 2020
  License - Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)
  Find the bot useful? Why not give it a star on Github?
  Find more information via the missionchiefbot.com website
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-06-23 14:47:54,361 Checking for updates...
2021-06-23 14:47:54,485 Your version is currently up to date!
XXX lineno: 176, opcode: 49
XXX lineno: 26, opcode: 117
XXX lineno: 39, opcode: 121
XXX lineno: 46, opcode: 48
XXX lineno: 255, opcode: 48

root@missionchief-nl-86566f4b97-bbftj:/Mission-Chief-Bot# python3.9 MissionChiefBot.py
Traceback (most recent call last):
  File "</Mission-Chief-Bot/MissionChiefBot.py>", line 3, in <module>
  File "<frozen MissionChiefBot>", line 36, in <module>
ModuleNotFoundError: No module named 'discord_webhook'

**Comment by jackbayliss** [comment]
You need to use python3.9 specifically, use python3.9 -m pip install discord_webhook

**Comment by jackbayliss** [comment]
@kaijehenstra You need to use python3.9 specifically, use python3.9 -m pip install discord_webhook

**Comment by kaijehenstra** [comment]
If I use the bash exec of the container it works with your method but if you specify CMD in the docker file and execute the script that way the operation stops (seen in logs) also no action is happening on the website

**Comment by jackbayliss** [comment]
Hmm, I've only seen this when there's a python version issue or a dir-specific issue. 

I will more than likely have to test it to see.

**Comment by jackbayliss** [comment]
This should be fixed in the latest beta
