### ISSUE TITLE
Patient / Prisoner Handoff not dispatching vehicles

### ISSUE THREAD

**Issue by A951951** [jackbayliss/Mission-Chief-Bot#111]
US Version

When Water Rescue missions complete and patients or prisoners are transported, the Patient / Prisoner Handoff missions are created.

Once the Water Rescue vehicles arrive at the Patient / Prisoner Handoff mission, they to not progress any further.  They sit there waiting for Ambulances or Police Cars.

If you manually send the Ambulance or Police Car, the missions will transport the patients or prisoners as normal.

I have let these handoff missions sit for approximately 24 hours.  During this time, all the Water Rescue vehicles are stuck until I manually send the vehicles, or the game times the missions out.

I have cleared all missions, so I do not have any screen shots available at this time.  I will let one or two sit and upload screen shots if you need them.

Thanks

**Comment by A951951** [comment]
updated info - when police vehicles are required, the transport is cancelled and the mission clears or updates if ambulances are still required.   Ambulance missions are still hanging with no ambulance dispatches.  I have one mission sitting stalled and will grab a screen shot once it approaches the 24 hour mark.

**Comment by jackbayliss** [comment]
@A951951 I don't actually play the game, but it's best if you can explain via screenshots. Missions could be stalled for various reasons, depends on the amount of vehicles you have available.  I'll leave this open so you can send screenshots etc, just ensure you exclude any usernames etc that could be used to identify you.

**Comment by A951951** [comment]
Thank you, I needed to let a couple of the missions stall again - screen shots follow
![Snapshot_221028055734](https://user-images.githubusercontent.com/116838226/198561293-7313362c-0457-4dd7-87a0-e38ecbc760b8.png)
![Snapshot_221028055858](https://user-images.githubusercontent.com/116838226/198561309-0a56c816-9542-4b8c-ba71-f5444c441d6a.png)

The first screen shot shows the list of stalled missions, the second shows the oldest mission that has been sitting since 6:42pm on 10/27/2022.  

I suspect that these are not getting caught because they are not actually assigned a mission ID and the requirements change each time one is created.

**Comment by MisterBFR** [comment]
Same on the French version
Patient/Prisoner Transfers
there is no mission ID

**Comment by jackbayliss** [comment]
I believe this is fixed! Please message me in discord On Oct 31, 2022 10:25, MisterBFR ***@***.***> wrote:
Same on the French version
Patient/Prisoner Transfers
there is no mission ID

**Comment by jackbayliss** [comment]
@A951951  @MisterBFR  If there's no mission id it's generally ignored, in this event what should happen ?

**Comment by A951951** [comment]
This is a fix to an issue that was created when they implemented the Water Rescue Missions.   You can't dispatch ambulances to ships and you can't take ships to hospitals, so they created the Patient / Prisoner Handoff Mission.

When you transport the patients or prisoners from a Water Rescue Mission, you are presented with a list of all the Water Rescue Stations, you select one of them.  At this point, the water rescue vehicle is dispatched to this Patient / Prisoner Mission.  This is not a one for one transport.  I will accept multiple vehicles from multiple missions.

Once the vehicles arrive, you are presented with the count of both prisoners and patients that need to be transported.   (you can send police cars as soon as you start the initial transport because they stay until cancelled - you can't send ambulanced at that time if you have auto release turned off because they are released as soon as they arrive).  

The Water Rescue vehicles stay attached to this mission until you transport the prisoners and patients, or cancel them.

Once you dispatch the police cars or ambulances, the missions are handled like any other transport request.

From the bots perspective, all prisoner transports are cancelled (I have not seen one transported yet.  All ambulances are never sent to a hospital or cancelled.

Hopefully this helps,  If you need additional information, or screen shots, please let me know.

**Comment by A951951** [comment]
Any Desk would be fine.  I will try to stage some scenarios to minimize the amount of time that may be required to see how it is working.  I will drop a note here once I have something.

**Comment by A951951** [comment]
I have three missions at the major stop/start points in the process.  One is ready to dispatch, one is ready to transfer patients and prisoners to handoff, and one is patients and prisoners in handoff ready to be transported to prison/hospital.  I have screen shots of the process up to this point as well.  I am available until 5:00pm US eastern time today if that works.  I am not sure how long these missions will stay before expiring.

**Comment by NotoriousBims** [comment]
This is being tested in beta right now. Should be ready hopefully soon.

**Comment by A951951** [comment]
Thank you, I am running the beta version right now, how do I get an the updated beta build to test?

**Comment by NotoriousBims** [comment]
Join our discord (you can find the link on the dashboard of the missionchiefbot.com website) and open a ticket. I can send it to you there.

**Comment by jackbayliss** [comment]
@A951951  Can you confirm this works? :)

**Comment by A951951** [comment]
as far as I can tell so far today, everything is working very well.  I have not found any dispatches where the arrival times on dispatched vehicles we outside what I would consider normal.  Thank you for this update, and allowing me to test the beta version.

**Comment by jackbayliss** [comment]
Awesome, great news 👍🏻
