### ISSUE TITLE
Can't seem to login to website to make a purchase

### ISSUE THREAD

**Issue by Feikovandijk** [jackbayliss/Mission-Chief-Bot#112]
Hi,
I've just registered my account on the website but every time I try to login it redirects me to the homepage without actually logging me in. Am I doing something wrong?

Cheers,

**Comment by jackbayliss** [comment]
Ensure you're logging in with email and pw, you'll notice dashboard appear in the nav if it's successful On Nov 1, 2022 17:56, Feiko van Dijk ***@***.***> wrote:
Hi,
I've just registered my account on the website but every time I try to login it redirects me to the homepage without actually logging me in. Am I doing something wrong?
Cheers,
