### ISSUE TITLE
Payed but can't find the discord

### ISSUE THREAD

**Issue by JackViking1** [jackbayliss/Mission-Chief-Bot#13]
Hey I Pay for the bot aka 1 $ but I can't find your discord or your dashboard under your webside.

**Comment by jackbayliss** [comment]
GitHub is not a supported method- only method is going via missionchiefbot.com 

>

**Comment by JackViking1** [comment]
How do I pay when I can't log in?

**Comment by jackbayliss** [comment]
You need to register an account - try using different information if you’re having trouble.
