### ISSUE TITLE
Send 1 required unit to own missions and share the call

### ISSUE THREAD

**Issue by NotoriousBims** [jackbayliss/Mission-Chief-Bot#19]
Make a setting to send 1 required unit to a mission, and share the call. 

Secondary requests - 

Have this setting follow all dispatch rules, for example: min/max credit
Have this setting send all required EMS units (including EMS chief if needed)

**Comment by NotoriousBims** [comment]
Another secondary request -

Have an option for the bot to finish shared mission within a certain time frame specified

**Comment by jackbayliss** [comment]
@NotoriousBims  Very reasonable, would this again just be a config option?

**Comment by NotoriousBims** [comment]
Yup, just another set of configurable options in the config file.

The options would be something like:

Alliance share:
Share own missions and send 1 required unit: true/false
Share own mission min credit: ######
share own mission max credit: #######
Share own mission send required ambulances (ems chief too): true/false
Share own mission time limit: 0-48 hours (bot will close mission inside this time limit by sending rest of missing units)

Optional:
Share overwrite:
Share own mission unit overwrite: (vehicle IDs)
Share own mission overwrite qty: ###

This will instead of sending any required unit, it will send the specified number of vehicles based on the vehicle ID.





For example:

Alliance share:
Share own missions and send 1 required unit: true
Share own mission min credit: 3999
share own mission max credit: 35000
Share own mission send required ambulances (ems chief too): true
Share own mission time limit: 6

So if a mission is 6000 credits, with 8 patients, the bot will share the mission, dispatch the closest required unit, dispatch 8 ambulances. Once the mission is open for 6 hours, the bot will send whatever is read in the missing text and close the call.
