### ISSUE TITLE
Newest Version (0.0.9.3) is crashing

### ISSUE THREAD

**Issue by meyerdominik** [jackbayliss/Mission-Chief-Bot#21]
INFO: 06/05/2020 07:07:40 sending mission for despatch 
INFO: 06/05/2020 07:07:40 Checking despatch for mission 
INFO: 06/05/2020 07:07:41 Exception list index out of range

after that, the Bot just crashed

**Comment by jackbayliss** [comment]
@meyerdominik  Will be patched at around 5PM GMT 👍

**Comment by jackbayliss** [comment]
Fixed with [0.0.9.4](https://github.com/jackbayliss/Mission-Chief-Bot/releases/tag/0.0.9.4)
