### ISSUE TITLE
Fix function for "transport_only_player" as it doesn't always follow the rules.

### ISSUE THREAD

**Issue by NotoriousBims** [jackbayliss/Mission-Chief-Bot#21]
Transport only player =

True = Only transports to player owned hospitals. If hospitals are full - release patient

False = Transport to player owned hospitals then to alliance hospitals (add function for prioritizing alliance before player owned hospitals?

**Comment by InternetMedicineMan** [comment]
Would love to see this fixed, I had high hopes when I saw the setting last night only to have my hopes dashed this morning when I woke up.

**Comment by jackbayliss** [comment]
@InternetMedicineMan  I'll take a look into it :) Just need a sample account so I can play with it.

**Comment by jackbayliss** [comment]
Should have fixed this! Gonna post a link in admin chat for review. DM me if you want to test @InternetMedicineMan

**Comment by InternetMedicineMan** [comment]
Nice. My hospitals are brimming full right now, and trying to drive 2 hours round trip. Do I just need shut it down, git pull, then restart the script?

**Comment by jackbayliss** [comment]
@InternetMedicineMan  Not quite! It's a testing build atm, I'll send it on Discord if you're using the Windows version :)

**Comment by InternetMedicineMan** [comment]
Ah no, was just trying to DM you and couldn't figure it out. I'm using the Linux Docker version. Can't wait to see it though.

**Comment by NotoriousBims** [comment]
> @InternetMedicineMan Not quite! It's a testing build atm, I'll send it on Discord if you're using the Windows version :)

Did we fix this? Looking to close this issue if possible.

**Comment by jackbayliss** [comment]
@NotoriousBims  There was no real fix, but seeing as I've smashed out the new fixes I will look at this today 👍🏻

**Comment by jackbayliss** [comment]
Believe this is fixed now, finally.. Please reach out to test. I will close.
