### ISSUE TITLE
Newest version (0.0.9.4) still crashing

### ISSUE THREAD

**Issue by wombatdotcom** [jackbayliss/Mission-Chief-Bot#25]
The bot is restarting itself after 3 missions in a loop.

Version: 0.0.9.4
Region: de

**Comment by jackbayliss** [comment]
@wombatdotcom  Not experienced any issues with my testing accounts unfortunately. It may be mission related, if you do the mission its crashing on manually it may continue. Alternatively if you email me the login details I can patch it :)

**Comment by Jimbob83** [comment]
Alos having issues with it crashing on UK server, running again to try and see if i can find what mission has caused it.

**Comment by jackbayliss** [comment]
@Jimbob83 Ive had it running on a few accounts with no issues UK wise, if you can provide a login via email i'll check it out :)

**Comment by meyerdominik** [comment]
Happens to me in DE too:

> INFO: 06/07/2020 08:49:22 Beginning despatch
INFO: 06/07/2020 08:49:22 500 mission
INFO: 06/07/2020 08:49:22 sending mission for despatch <0>
INFO: 06/07/2020 08:49:22 Checking despatch for mission <0>
INFO: 06/07/2020 08:49:22 Mission <0>meets the requirements- attempting to send.
INFO: 06/07/2020 08:49:22 Attempting to despatch <0>
INFO: 06/07/2020 08:49:23 <0>despatched
INFO: 06/07/2020 08:49:33 476 mission
INFO: 06/07/2020 08:49:33 sending mission for despatch <1>
INFO: 06/07/2020 08:49:33 Checking despatch for mission <1>
INFO: 06/07/2020 08:49:33 Exception ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 

after that the bot just restarted

**Comment by Jimbob83** [comment]
> @Jimbob83 Ive had it running on a few accounts with no issues UK wise, if you can provide a login via email i'll check it out :)

I would prefer not to share my login TBH, If i send over the debug.txt would this be of any help?

**Comment by jackbayliss** [comment]
@meyerdominik the issue you're having `Connection aborted.', RemoteDisconnected('Remote end closed connection without response')` is based on the missionchief server closing the response, this could be due to your internet or some kind of anti spam if you've set your limits low.

@Jimbob83 I'm removing the updated changes, and re releasing tonight, as the updates turned out to not be correct i.e we were taking a number for ambulances that weren't actually true. So, after that the issues should be fixed.

**Comment by meyerdominik** [comment]
@jackbayliss the curious thing is, that everything works fine with the verion 0.0.9.2 😄 
I'll invesigate further, in the next version 👍

**Comment by jackbayliss** [comment]
@meyerdominik  It may be related in that case, this will be fixed in the next patch- my apologies for the inconvenience.  - Closing as patched, just need to release.
