### ISSUE TITLE
Crashing on version 0.0.9.6

### ISSUE THREAD

**Issue by Jimbob83** [jackbayliss/Mission-Chief-Bot#28]
Hi Jack

Getting an issue with the program crashing, it looks to be an issue with the vehicle type for Armed Response Vehicles (on UK server).

> INFO: 06/11/2020 07:22:08 Attempting login
> INFO: 06/11/2020 07:22:09 Checking for transport
> INFO: 06/11/2020 07:22:09 Checking for ambulance transport
> INFO: 06/11/2020 07:22:11 Checking for prisoners
> INFO: 06/11/2020 07:22:12 22missions found
> INFO: 06/11/2020 07:22:12 Beginning despatch
> INFO: 06/11/2020 07:22:12 176 mission
> INFO: 06/11/2020 07:22:12 armed response personnel was not found in the links.json
> INFO: 06/11/2020 07:22:12 sending mission for despatch 16534426
> INFO: 06/11/2020 07:22:12 Checking despatch for mission 16534426
> INFO: 06/11/2020 07:22:13 Exception 'min_sleep_per_select'

This is what I am getting in the debug file. The program then restarts and same thing happens again.

The Mission No 16534426 was for UNAUTHORIZED POSSESSION OF WEAPONS

Thanks for the regular updates on this, and the fast response to making the changes.

Jim

**Comment by Jimbob83** [comment]
Hi Jack,

Sorry crashing was my fault, I had copied over my old config.ini file (being lazy) and had not noticed it had been updated in version 0.0.9.6.

The issue of not detecting the Armed Response Vehicle is still there, and it is not dispatching them.

Thanks

Jim

**Comment by jackbayliss** [comment]
@Jimbob83 The config has indeed updated, but at least you fixed it.

You need to add : ` "armed response personnel" :  [13]`  to your links.json- the issue is the armed response vehicle (ARV) was added manually by players so new missions aren't updated and default to armed response personnel. I will update the json to stop this issue.

**Comment by Jimbob83** [comment]
@jackbayliss thanks.

[debug.txt](https://github.com/jackbayliss/Mission-Chief-Bot/files/4767078/debug.txt)

Getting an error now uploaded my debug file. About a read error, also getting on 0.0.9.5 never had this issue before.

**Comment by jackbayliss** [comment]
@Jimbob83  Yes, it's happening for a few players- it's also happening on the mission chief app. I believe the servers are having issues because of the promotions and what not. It's not related to the bot itself :)

**Comment by Jimbob83** [comment]
@jackbayliss spot on, ios app has been rotten for weeks, keeps jumping all over the shop.
