### ISSUE TITLE
 2021-04-05 17:16:39,745 Issue with JSON file: 575.json please check it.

### ISSUE THREAD

**Issue by nickstop** [jackbayliss/Mission-Chief-Bot#3]
It always says `2021-04-05 17:16:39,745 Issue with JSON file: 575.json please check it.`

**Comment by jackbayliss** [comment]
Which region? Have you tried deleting 575.json and re running? I

**Comment by jackbayliss** [comment]
@nickstop  Have you tried deleting the json file and letting the bot re-download? Which region is this?

**Comment by nickstop** [comment]
Now it works
