### ISSUE TITLE
ignore planned missions?

### ISSUE THREAD

**Issue by Kulifloerkus** [jackbayliss/Mission-Chief-Bot#3]
Is there a way to ignore the onw planned missions?

**Comment by jackbayliss** [comment]
You can ignore missions by adding the mission names into the missionignorelist, in the json folder.

**Comment by Kulifloerkus** [comment]
Ok, then I have to find out what all the planned missions are called.

**Comment by jackbayliss** [comment]
What is a planned mission? I.E a mission that's not due yet?

**Comment by Kulifloerkus** [comment]
![planedMissions](https://user-images.githubusercontent.com/64958878/81332833-f6a07000-90a3-11ea-8908-b08e436a3e10.PNG)

**Comment by jackbayliss** [comment]
Timed missions are now ignored with [0.0.8](https://github.com/jackbayliss/Mission-Chief-Bot/releases/tag/0.0.8)- not sure if that's the same thing. But if not you can enter the mission name in your ignored list.
