### ISSUE TITLE
Bot tries to dispatch vehicles that are not needed, since the amount of that building type is not reached yet 

### ISSUE THREAD

**Issue by meyerdominik** [jackbayliss/Mission-Chief-Bot#31]
A simple example is the mission 345 (https://www.leitstellenspiel.de/einsaetze/345) "Höhenrettung am Fahrgeschäft"

Spawn-requirements for the mission are: 
>buildingype:		minimum amount
Feuerwachen : 	3
Rettungswachen:	1
Polizeiwachen: 	1

Vehicle-requirements for that mission:
>vehicletype:		amount needed
Löschfahrzeuge:	2 
Drehleitern:		1 
ELW 1:			1
Rüstwagen:		1 
GW-Höhenrettung:	1
Streifenwagen:	1
RTW	:			1

But certain vehicletype are not needed yet, since the minimum-amount of the buildingtype is maybe not reached yet.
>vehicletype:		minimum of that building type needed
ELW 1:			6 Feuerwachen
Rüstwagen: 		4 Feuerwachen
GW-Höhenrettung: 12 Feuerwachen

If a mission like that requires vehicletypes, that are not needed yet, they are not required for misson-completion!

**Comment by jackbayliss** [comment]
I see, my only suggestion for now would be to manually adjust the requirements and remove the vehicles you don't have. This is a simple find and replace, and should take a few seconds at most.

**Comment by Arciah** [comment]
Ive got problem that no units are dispatched anytime, just check for transport victioms or prisoners every 2 min

**Comment by Arciah** [comment]
> Ive got problem that no units are dispatched anytime, just check for transport victioms or prisoners every 2 min

19/06/2020 10:11:20: Sleeping for 36.606787083299125 seconds
19/06/2020 10:11:56: Generating Missions...
19/06/2020 10:11:56: Checking for any ambulance transport requests.
19/06/2020 10:11:56: 0 ambulance transports found
19/06/2020 10:11:56: Checking for any prisoners.
19/06/2020 10:11:56: 0 prisoners found
19/06/2020 10:11:56: Building 55 missions...
19/06/2020 10:11:56: 24 missions found
19/06/2020 10:11:56: Retrying any missions that failed...
19/06/2020 10:11:56: Checking for any ambulance transport requests.
19/06/2020 10:11:56: 0 ambulance transports found
19/06/2020 10:11:56: Checking for any prisoners.
19/06/2020 10:11:57: 0 prisoners found
19/06/2020 10:11:57: Sleeping for 110.91083718106736 seconds

**Comment by jackbayliss** [comment]
@Arciah  Please create a separate thread. As for this issue, you’ll have to manually alter the requirements for what you don’t have.
