### ISSUE TITLE
Station hire exclusions

### ISSUE THREAD

**Issue by NotoriousBims** [jackbayliss/Mission-Chief-Bot#32]
Building ignore list for training. As bot tries to hire for hospitals and other buildings not needed which slows down the process.

**Comment by jackbayliss** [comment]
Great idea, let's create a json for this with the building name to exclude.

**Comment by jackbayliss** [comment]
This is done, no json needed. Buildings with 0 staff specify such, and those with 0 staff are now auto excluded.
