### ISSUE TITLE
New trucks in pl version

### ISSUE THREAD

**Issue by Arciah** [jackbayliss/Mission-Chief-Bot#32]
Hi there !

As requestes im creating new topic.

We have 2 type of truck what we are able to buy. One is called GBARt - that is truck what provide 2 possibile jobs, fire engine and technical truck. Also have own group called GBARt.

This truck can response for mission when you require one of those:
"samochody po\u017carnicze": [0, 1],
  "samochody ratownictwa technicznego": [4],

Also we have new truck called Podnośnik hydrauliczny, similar situation but can response also as a fire engine and leader. In this situation:
"sp wysoko\u015bciowe": [2],
"samochody po\u017carnicze": [0, 1],

Can you please tell me if there is possibility to add those trucks ? Ive got 25 GBARt atm and need to send them manualy

Thanks in advance

**Comment by Arciah** [comment]
Yes, correct!

**Comment by jackbayliss** [comment]
@Arciah  Visit [here](https://www.operatorratunkowy.pl/api/vehicles) and tell me the vehicle_type for Podnośnik hydrauliczny and GBARt

**Comment by Arciah** [comment]
I found this:

{"id":361774,"caption":"GBARt","building_id":200307,"vehicle_type":12,"fms_real":2,"fms_show":2,"vehicle_type_caption":null},{"id":514322,"caption":"GBARt","building_id":28356,"vehicle_type":12,"fms_real":2,"fms_show":2,"vehicle_type_caption":null},{"id":804739,"caption":"Podnośnik hydrauliczny","building_id":420049,"vehicle_type":13,"fms_real":2,"fms_show":2,"vehicle_type_caption":null},{"id":805419,"caption":"Podnośnik hydrauliczny","building_id":28356,"vehicle_type":13,"fms_real":2,"fms_show":2,"vehicle_type_caption":null},{"id":804736,"caption":"GBARt","building_id":420049,"vehicle_type":12,"fms_real":2,"fms_show":2,"vehicle_type_caption":null}

**Comment by jackbayliss** [comment]
@Arciah  OK great, now all you need to do is change the following in the links:
```
"samochody po\u017carnicze": [0, 1,12]
"samochody ratownictwa technicznego": [4,12]
"sp wysoko\u015bciowe": [2,13],
"samochody po\u017carnicze": [0, 1,13]
```

Let me know if it works - I'll make it live for PL.

**Comment by Arciah** [comment]
Going to change ill let you know in few min

**Comment by jackbayliss** [comment]
@Arciah  No rush, just change your links.json to add the new ids

**Comment by Arciah** [comment]
![image](https://user-images.githubusercontent.com/67099386/85162872-50c75000-b262-11ea-8d75-ed993b4dd400.png)

Not sending any units now

**Comment by Arciah** [comment]
thats not true, i have everything avaible in base, this is how file looks like:

{
  "samochody po\u017carnicze": [0, 1, 12, 13],
  "samochody oficera operacyjnego": [3],
  "samochody ratownictwa technicznego": [4, 12],
  "cysterny z wod\u0105": [6],
  "sp wysoko\u015bciowe": [2, 13],
  "sp rchem": [7],
  "samochody spgaz": [10],
  "radiowozy": [8, 16],
  "maks. pacjenci": [5],
  "samochody dowodzenia i łączności" : [11]
}

**Comment by Arciah** [comment]
and now something new:
![image](https://user-images.githubusercontent.com/67099386/85163245-d6e39680-b262-11ea-9899-37f1e8255845.png)

**Comment by jackbayliss** [comment]
@Arciah  For example Wyapdek Motocyklowy : 

{"missionId": "103", "missionName": "Wypadek motocyklowy", "requirements": [{"requirement": "samochody po\u017carnicze", "qty": "3"}, {"requirement": "samochody oficera operacyjnego", "qty": "1"}, {"requirement": "radiowozy", "qty": "1"}, {"requirement": "maks. pacjenci", "qty": "2"}]}

You can see it needs 7 units, so you could be missing any particular one. I would suggest making sure you have enough ambulances.

**Comment by Arciah** [comment]
Thing is, now i got everything in base cus its not sending any vehicle now.

This is statistic of my bases:

![image](https://user-images.githubusercontent.com/67099386/85163675-7acd4200-b263-11ea-8766-ea23384c3d71.png)

**Comment by MC-bot-test** [comment]
Excuse me if I'm incorrect, because I only speak english, but it looks like in your **links** file you have the following

"maks. pacjenci": [5], (in english = max.patient [5] )

when it should be (in english) "ambulance": [5] - I can see "Ambulans P" in your base so I assume it is this one?

See if that helps - apologies if it doesn't.

**Comment by Arciah** [comment]
Ambulans P - is commun ambulance what carry 2 paramedic, we also have Ambulans S what carry 2 paramedic and doctor, not avaible in game atm

**Comment by MC-bot-test** [comment]
Yes, so you need to have that in your **links** file as above, **not maks. pacjenci** linked to vehicle type 5

**change** - "maks. pacjenci": [5], - **to**- "Ambulans P"; [5],

**Comment by Arciah** [comment]
Damn yee you are right going to change and give update

**Comment by Arciah** [comment]
there is also one more error  "radiowozy": [8], should be radiowóz but i have no clue how to write "ó" in dos language something like po\u017carnicze \u017 = ż

**Comment by Arciah** [comment]
found this 

ó
C/C++/Java source code | "\u00F3"

**Comment by Arciah** [comment]
> Yes, so you need to have that in your **links** file as above, **not maks. pacjenci** linked to vehicle type 5
> 
> **change** - "maks. pacjenci": [5], - **to**- "Ambulans P"; [5],

After changing this im unable to unload patient

**Comment by Arciah** [comment]
> > Yes, so you need to have that in your **links** file as above, **not maks. pacjenci** linked to vehicle type 5
> > **change** - "maks. pacjenci": [5], - **to**- "Ambulans P"; [5],
> 
> After changing this im unable to unload patient

**Comment by Arciah** [comment]
I changed back to maks.pacjenci found 7 ambulances but im unable to unload due to no hospital, im using hospital in my alliance

**Comment by MC-bot-test** [comment]
Sorry, can't help with that one.

**Comment by Arciah** [comment]
Now i stuck with

20/06/2020 15:04:02: Sleeping for 3.2682438225780883 seconds
20/06/2020 15:04:05: No available hospitals.
20/06/2020 15:04:05: Attempting to release patient..
20/06/2020 15:04:05: Unable to release patient.

**Comment by jackbayliss** [comment]
There may have been some code changes causing this issue- I’ll look into it. Also, the links must follow the missions requirements json so - that could be why particular vehicles aren’t working

**Comment by Arciah** [comment]
[debug.txt](https://github.com/jackbayliss/Mission-Chief-Bot/files/4808278/debug.txt)

New thing, after 10-15 min it switching off no idea why

**Comment by jackbayliss** [comment]
@Arciah  Crashing is linked to : [this](https://github.com/jackbayliss/Mission-Chief-Bot/issues/33#issuecomment-647030710) which has been fixed on my version.

As for the PL vehicles, it should be working fine

**Comment by Arciah** [comment]
# Just show the players missions, ignore alliance- set true if you want to ignore alliance.
show_own = false

i have like this, and its not sending any vehicle to aliance mission, even if they need operation only or operational and 2 police cars, aliance mission stay there forever or until i send unist manualy

**Comment by jackbayliss** [comment]
@Arciah  Alliance missions definitely work- it might be that they have units on route. They'll only be loaded in if the mission is red (fresh).

**Comment by Arciah** [comment]
Got new cars but i need to wait till morning, cus i need police academy, got like swat team and k-9 unit. Ill give you update tomorrow about group and names of vehicles

**Comment by Arciah** [comment]
{"id":813900,"caption":"Jednostka K-9","building_id":65771,"vehicle_type":16,"fms_real":3,"fms_show":3,"vehicle_type_caption":null}

Thats k-9 unit

**Comment by Arciah** [comment]
It look like this now, and for me it works

{
  "samochody po\u017carnicze": [0, 1, 12, 13],
  "samochody oficera operacyjnego": [3],
  "samochody ratownictwa technicznego": [4, 12],
  "cysterny z wod\u0105": [6],
  "sp wysoko\u015bciowe": [2, 13],
  "sp rchem": [7],
  "samochody spgaz": [10],
  "radiowozy": [8],
  "Ambulans P": [5],
  "ambulanse": [5],
  "maks. pacjenci": [5],
  "Jednostka K-9": [16],
  "samochody dowodzenia i \u0142\u0105czno\u015Bci" : [11]
}

**Comment by jackbayliss** [comment]
@Arciah  Make sure the k-9 unit is in the mission requirements.

**Comment by Arciah** [comment]
> @Arciah Make sure the k-9 unit is in the mission requirements.

Yes its new mission for me, also i have problem on other account. I just made a copy of that main folder just changed account details but on second account bot is not sending anything, i have ervything inside bases and it keep sending msg i have not enought units avaible.  For example fire in building need 3 trucks and leder i have 6 leders in base and about 20+ trucks rdy to dispatch

23/06/2020 20:21:12: Generating Missions...
23/06/2020 20:21:13: Checking for any ambulance transport requests.
23/06/2020 20:21:13: 0 ambulance transports found
23/06/2020 20:21:13: Checking for any prisoners.
23/06/2020 20:21:13: 0 prisoners found
23/06/2020 20:21:13: Building 41 missions...
23/06/2020 20:21:13: 22 missions found
23/06/2020 20:21:13: Sleeping for 4.917879286041828 seconds
23/06/2020 20:21:17: Sleeping for 2.8676082087078525 seconds
23/06/2020 20:21:19: Sleeping for 2.487289030892282 seconds
23/06/2020 20:21:21: Mission Pożar pomieszczenia was not despatched
23/06/2020 20:21:21: qty we have : 3 - qty required 4
23/06/2020 20:21:21: Sleeping for 8.393206373107695 seconds
23/06/2020 20:21:30: Sleeping for 1.6354931175817606 seconds
23/06/2020 20:21:31: Sleeping for 1.9686220109781134 seconds
23/06/2020 20:21:32: Sleeping for 4.615104427094321 seconds
23/06/2020 20:21:36: Mission Pożar piwnicy was not despatched
23/06/2020 20:21:36: qty we have : 4 - qty required 6
23/06/2020 20:21:36: Sleeping for 9.908841056510514 seconds
23/06/2020 20:21:47: Sleeping for 4.6575477886444645 seconds
23/06/2020 20:21:51: Sleeping for 4.9794606945247715 seconds
23/06/2020 20:21:55: Sleeping for 1.4315874397772488 seconds
23/06/2020 20:21:56: Mission Pożar piwnicy was not despatched
23/06/2020 20:21:56: qty we have : 4 - qty required 6
23/06/2020 20:21:56: Sleeping for 11.075843505311571 seconds
23/06/2020 20:22:07: Sleeping for 2.839236020944282 seconds
23/06/2020 20:22:09: Sleeping for 2.1439544473087055 seconds
23/06/2020 20:22:11: Sleeping for 3.89175917259371 seconds
23/06/2020 20:22:14: Mission Pożar piwnicy was not despatched
23/06/2020 20:22:14: qty we have : 4 - qty required 6
23/06/2020 20:22:14: Sleeping for 2.4502090879499105 seconds
23/06/2020 20:22:17: Sleeping for 3.485225761472431 seconds
23/06/2020 20:22:20: Sleeping for 2.8114749997503923 seconds
23/06/2020 20:22:22: Sleeping for 3.4185992054758914 seconds
23/06/2020 20:22:25: Mission Pożar pomieszczenia was not despatched
23/06/2020 20:22:25: qty we have : 3 - qty required 4
23/06/2020 20:22:25: Sleeping for 3.578397336249303 seconds
23/06/2020 20:22:30: Sleeping for 2.442023392317612 seconds
23/06/2020 20:22:32: Sleeping for 1.0131916645561558 seconds
23/06/2020 20:22:33: Sleeping for 1.3108451857352321 seconds
23/06/2020 20:22:34: Mission Pożar pomieszczenia was not despatched
23/06/2020 20:22:34: qty we have : 3 - qty required 4
23/06/2020 20:22:34: Sleeping for 17.14200675186772 seconds
23/06/2020 20:22:51: Sleeping for 4.313367057764246 seconds
23/06/2020 20:22:55: Sleeping for 3.23960056196251 seconds
23/06/2020 20:22:58: Sleeping for 3.2859590053383134 seconds
23/06/2020 20:23:01: Mission Pożar pomieszczenia was not despatched
23/06/2020 20:23:01: qty we have : 3 - qty required 4
23/06/2020 20:23:01: Sleeping for 8.491765592566653 seconds
23/06/2020 20:23:11: Sleeping for 2.9741559232033996 seconds
23/06/2020 20:23:13: Sleeping for 3.436089376361756 seconds
23/06/2020 20:23:16: Sleeping for 3.714243859738806 seconds
23/06/2020 20:23:19: Mission Pożar pomieszczenia was not despatched
23/06/2020 20:23:19: qty we have : 3 - qty required 4
23/06/2020 20:23:19: Sleeping for 15.687942852445344 seconds
23/06/2020 20:23:35: Sleeping for 2.8553357452123795 seconds
23/06/2020 20:23:37: Sleeping for 4.505685686281838 seconds
23/06/2020 20:23:41: Sleeping for 2.106710117196224 seconds
23/06/2020 20:23:43: Mission Pożar pomieszczenia was not despatched
23/06/2020 20:23:43: qty we have : 3 - qty required 4
23/06/2020 20:23:43: Sleeping for 16.216096408147532 seconds
23/06/2020 20:24:00: Sleeping for 1.6419094118863686 seconds
23/06/2020 20:24:01: Sleeping for 2.529058602538543 seconds
23/06/2020 20:24:03: Sleeping for 4.583568509387835 seconds
23/06/2020 20:24:07: Mission Pożar pomieszczenia was not despatched
23/06/2020 20:24:07: qty we have : 3 - qty required 4
23/06/2020 20:24:07: Sleeping for 13.449359095866965 seconds
23/06/2020 20:24:21: Sleeping for 4.237590773538804 seconds
23/06/2020 20:24:25: Sleeping for 1.1110156934677469 seconds
23/06/2020 20:24:26: Sleeping for 2.1555977613889237 seconds
23/06/2020 20:24:28: Mission Pożar pomieszczenia was not despatched
23/06/2020 20:24:28: qty we have : 3 - qty required 4
23/06/2020 20:24:28: Sleeping for 7.732525628168393 seconds
23/06/2020 20:24:36: Sleeping for 4.356097582040546 seconds
23/06/2020 20:24:41: Sleeping for 2.2558155304470295 seconds
23/06/2020 20:24:43: Sleeping for 1.7705264915818857 seconds
23/06/2020 20:24:44: Mission Pożar pomieszczenia was not despatched
23/06/2020 20:24:44: qty we have : 3 - qty required 4
23/06/2020 20:24:44: Sleeping for 16.646387005103136 seconds
23/06/2020 20:25:01: Sleeping for 2.3835263998974834 seconds
23/06/2020 20:25:03: Sleeping for 4.032007590904236 seconds
23/06/2020 20:25:07: Sleeping for 1.295370510134891 seconds
23/06/2020 20:25:08: Mission Pożar pomieszczenia was not despatched
23/06/2020 20:25:08: qty we have : 3 - qty required 4
23/06/2020 20:25:08: Sleeping for 17.92711165198567 seconds
23/06/2020 20:25:26: Sleeping for 4.92919479106518 seconds
23/06/2020 20:25:30: Sleeping for 3.7932481616404643 seconds
23/06/2020 20:25:33: Sleeping for 1.314332388987808 seconds
23/06/2020 20:25:34: Mission Pożar pomieszczenia was not despatched
23/06/2020 20:25:34: qty we have : 3 - qty required 4
23/06/2020 20:25:34: Sleeping for 6.060328053615092 seconds
23/06/2020 20:25:41: Sleeping for 3.562803496203653 seconds
23/06/2020 20:25:44: Sleeping for 4.889777138268498 seconds
23/06/2020 20:25:48: Sleeping for 3.644626635652492 seconds
23/06/2020 20:25:51: Mission Pożar piwnicy was not despatched
23/06/2020 20:25:51: qty we have : 4 - qty required 6
23/06/2020 20:25:51: Sleeping for 3.195039568654332 seconds
23/06/2020 20:25:55: Sleeping for 3.7446894009519287 seconds
23/06/2020 20:25:58: Sleeping for 2.250767352078477 seconds
23/06/2020 20:26:00: Sleeping for 1.2777038938349494 seconds
23/06/2020 20:26:01: Mission Pożar piwnicy was not despatched
23/06/2020 20:26:01: qty we have : 4 - qty required 6
23/06/2020 20:26:01: Sleeping for 19.09034330823427 seconds

**Comment by Arciah** [comment]
INFO: 06/23/2020 08:20:17 Attempting login
INFO: 06/23/2020 08:20:21 Checking for transport
INFO: 06/23/2020 08:20:21 Checking for ambulance transport
INFO: 06/23/2020 08:20:21 Checking for prisoners
INFO: 06/23/2020 08:20:21 22missions found
INFO: 06/23/2020 08:20:21 Beginning despatch
INFO: 06/23/2020 08:20:22 Checking for transport
INFO: 06/23/2020 08:20:22 Checking for ambulance transport
INFO: 06/23/2020 08:20:22 Checking for prisoners
INFO: 06/23/2020 08:20:22 22missions found
INFO: 06/23/2020 08:20:22 Beginning despatch
INFO: 06/23/2020 08:21:06 Attempting login
INFO: 06/23/2020 08:21:12 Checking for transport
INFO: 06/23/2020 08:21:13 Checking for ambulance transport
INFO: 06/23/2020 08:21:13 Checking for prisoners
INFO: 06/23/2020 08:21:13 22missions found
INFO: 06/23/2020 08:21:13 Beginning despatch
INFO: 06/23/2020 08:21:13 5 mission
INFO: 06/23/2020 08:21:13 sending mission for despatch 34084143
INFO: 06/23/2020 08:21:13 Checking despatch for mission 34084143
INFO: 06/23/2020 08:21:21 Mission34084143 does not meet the requirements.
INFO: 06/23/2020 08:21:30 20 mission
INFO: 06/23/2020 08:21:30 sending mission for despatch 34084237
INFO: 06/23/2020 08:21:30 Checking despatch for mission 34084237
INFO: 06/23/2020 08:21:36 Mission34084237 does not meet the requirements.
INFO: 06/23/2020 08:21:46 20 mission
INFO: 06/23/2020 08:21:46 sending mission for despatch 34085451
INFO: 06/23/2020 08:21:46 Checking despatch for mission 34085451
INFO: 06/23/2020 08:21:56 Mission34085451 does not meet the requirements.
INFO: 06/23/2020 08:22:07 20 mission
INFO: 06/23/2020 08:22:07 sending mission for despatch 34086161
INFO: 06/23/2020 08:22:07 Checking despatch for mission 34086161
INFO: 06/23/2020 08:22:14 Mission34086161 does not meet the requirements.
INFO: 06/23/2020 08:22:17 5 mission
INFO: 06/23/2020 08:22:17 sending mission for despatch 34087194
INFO: 06/23/2020 08:22:17 Checking despatch for mission 34087194
INFO: 06/23/2020 08:22:25 Mission34087194 does not meet the requirements.
INFO: 06/23/2020 08:22:29 5 mission
INFO: 06/23/2020 08:22:29 sending mission for despatch 34088598
INFO: 06/23/2020 08:22:29 Checking despatch for mission 34088598
INFO: 06/23/2020 08:22:34 Mission34088598 does not meet the requirements.
INFO: 06/23/2020 08:22:51 66 mission
INFO: 06/23/2020 08:22:51 sending mission for despatch 34088891
INFO: 06/23/2020 08:22:51 Checking despatch for mission 34088891
INFO: 06/23/2020 08:23:01 Mission34088891 does not meet the requirements.
INFO: 06/23/2020 08:23:10 66 mission
INFO: 06/23/2020 08:23:10 sending mission for despatch 34089165
INFO: 06/23/2020 08:23:10 Checking despatch for mission 34089165
INFO: 06/23/2020 08:23:19 Mission34089165 does not meet the requirements.
INFO: 06/23/2020 08:23:34 5 mission
INFO: 06/23/2020 08:23:34 sending mission for despatch 34089652
INFO: 06/23/2020 08:23:34 Checking despatch for mission 34089652
INFO: 06/23/2020 08:23:43 Mission34089652 does not meet the requirements.
INFO: 06/23/2020 08:23:59 66 mission
INFO: 06/23/2020 08:23:59 sending mission for despatch 34097082
INFO: 06/23/2020 08:23:59 Checking despatch for mission 34097082
INFO: 06/23/2020 08:24:07 Mission34097082 does not meet the requirements.
INFO: 06/23/2020 08:24:20 5 mission
INFO: 06/23/2020 08:24:20 sending mission for despatch 34098516
INFO: 06/23/2020 08:24:20 Checking despatch for mission 34098516
INFO: 06/23/2020 08:24:28 Mission34098516 does not meet the requirements.
INFO: 06/23/2020 08:24:36 5 mission
INFO: 06/23/2020 08:24:36 sending mission for despatch 34100997
INFO: 06/23/2020 08:24:36 Checking despatch for mission 34100997
INFO: 06/23/2020 08:24:44 Mission34100997 does not meet the requirements.
INFO: 06/23/2020 08:25:00 5 mission
INFO: 06/23/2020 08:25:00 sending mission for despatch 34104132
INFO: 06/23/2020 08:25:00 Checking despatch for mission 34104132
INFO: 06/23/2020 08:25:08 Mission34104132 does not meet the requirements.
INFO: 06/23/2020 08:25:26 66 mission
INFO: 06/23/2020 08:25:26 sending mission for despatch 34110616
INFO: 06/23/2020 08:25:26 Checking despatch for mission 34110616
INFO: 06/23/2020 08:25:34 Mission34110616 does not meet the requirements.
INFO: 06/23/2020 08:25:41 20 mission
INFO: 06/23/2020 08:25:41 sending mission for despatch 34114043
INFO: 06/23/2020 08:25:41 Checking despatch for mission 34114043
INFO: 06/23/2020 08:25:51 Mission34114043 does not meet the requirements.
INFO: 06/23/2020 08:25:54 20 mission
INFO: 06/23/2020 08:25:54 sending mission for despatch 34116145
INFO: 06/23/2020 08:25:54 Checking despatch for mission 34116145
INFO: 06/23/2020 08:26:01 Mission34116145 does not meet the requirements.
INFO: 06/23/2020 08:26:20 20 mission
INFO: 06/23/2020 08:26:20 sending mission for despatch 34116816
INFO: 06/23/2020 08:26:20 Checking despatch for mission 34116816

**Comment by jackbayliss** [comment]
@Arciah  These logs don't really help unfortunately,  You have to be missing a vehicle- I would suggest PM'img me on Discord so I can help you properly, as it's difficult to advise from here.

**Comment by jackbayliss** [comment]
Closing, spoke to @Arciah via Discord to explain how the bot functions. Was missing ambo units.
