### ISSUE TITLE
Integration über Python. Token über Config. https://healthchecks.io

### ISSUE THREAD

**Issue by NotoriousBims** [jackbayliss/Mission-Chief-Bot#33]
Integration über Python. Token über Config. https://healthchecks.io

**Comment by jackbayliss** [comment]
uhhhhhh -- not sure why this is a good feature?

**Comment by NotoriousBims** [comment]
I think its like a status monitor to check if its running or not. I don't really know honestly. Close the issue so it is taken off the board if you don't want to deal with it.
