### ISSUE TITLE
Unable to release patients

### ISSUE THREAD

**Issue by csBlackWolf** [jackbayliss/Mission-Chief-Bot#34]
The BOT can't automatically release patient when no hospital is available.

Output:
> 24/06/2020 00:21:00: Checking for any prisoners.
> 24/06/2020 00:21:00: 0 prisoners found
> 24/06/2020 00:21:00: Sleeping for 18.186184328507284 seconds
> 24/06/2020 00:21:18: Generating Missions...
> 24/06/2020 00:21:18: Checking for any ambulance transport requests.
> 24/06/2020 00:21:18: 2 ambulance transports found
> 24/06/2020 00:21:18: Sleeping for 4.680568127161758 seconds
> 24/06/2020 00:21:22: No available hospitals.
> 24/06/2020 00:21:22: Attempting to release patient..
> 24/06/2020 00:21:22: Unable to release patient.
> 24/06/2020 00:21:22: Sleeping for 4.9881782190004955 seconds
> 24/06/2020 00:21:26: No available hospitals.
> 24/06/2020 00:21:26: Attempting to release patient..
> 24/06/2020 00:21:26: Unable to release patient.
> 24/06/2020 00:21:26: Checking for any prisoners.
> 24/06/2020 00:21:26: 0 prisoners found
> 24/06/2020 00:21:26: Building 36 missions...
> 24/06/2020 00:21:26: 2 missions found
> Herzkreislaufprobleme has no vehicles available for sending-- ignoring.
> See URL: https://www.leitstellenspiel.de/missions/1469559166
> 24/06/2020 00:21:26: Sleeping for 7.314895216477288 seconds
> Arbeitsunfall im Garten has no vehicles available for sending-- ignoring.
> See URL: https://www.leitstellenspiel.de/missions/1469725312
> 24/06/2020 00:22:05: Sleeping for 15.109973471457414 seconds
> 24/06/2020 00:22:21: Retrying any missions that failed...
> 24/06/2020 00:22:21: Checking for any ambulance transport requests.
> 24/06/2020 00:22:21: 2 ambulance transports found
> 24/06/2020 00:22:21: Sleeping for 1.4006045519974135 seconds
> 24/06/2020 00:22:22: No available hospitals.
> 24/06/2020 00:22:22: Attempting to release patient..
> 24/06/2020 00:22:22: Unable to release patient.
> 24/06/2020 00:22:22: Sleeping for 3.6945412331089496 seconds
> 24/06/2020 00:22:25: No available hospitals.
> 24/06/2020 00:22:25: Attempting to release patient..
> 24/06/2020 00:22:25: Unable to release patient.
> 24/06/2020 00:22:25: Checking for any prisoners.
> 24/06/2020 00:22:25: 0 prisoners found
> 24/06/2020 00:22:25: Sleeping for 101.67919799823758 seconds

[debug.txt](https://github.com/jackbayliss/Mission-Chief-Bot/files/4822290/debug.txt)

**Comment by jackbayliss** [comment]
@csBlackWolf  Thanks for the report, this has been fixed- will be patched in the new upcoming release. 👍
