### ISSUE TITLE
POIGen - random POIs mode

### ISSUE THREAD

**Issue by NotoriousBims** [jackbayliss/Mission-Chief-Bot#37]
Update the POI generator with a new mode. 

Mode 1: Place accurate POIs within a certain radius around a building.
Mode 2: Places randomly, 1* of each type of POI within a certain radius around a building. 

* = maybe a specified number of POIs

**Comment by jackbayliss** [comment]
Mode 2 is implemented, it will place each type around the radius of the building.

**Comment by NotoriousBims** [comment]
How many of each type around the radius of the building?

**Comment by jackbayliss** [comment]
It’s set to 1 of each, but I can make it editable I guess

**Comment by NotoriousBims** [comment]
That can be a feature for the future. 1 is great for now.

**Comment by jackbayliss** [comment]
Believe done
