### ISSUE TITLE
OTL's not being dispatched despite being in links.json and a mission requirement. (UK)

### ISSUE THREAD

**Issue by Whitchit** [jackbayliss/Mission-Chief-Bot#39]
So I am having an issue on the UK server where Operational Team Leaders (api/vehicles:20) are not being dispatched by the bot even though they are included in links.json and a mission requirement in missions 148.json and 149.json and I am unsure how to go about rectifying this?

**Comment by jackbayliss** [comment]
@Whitchit  Operational Team Leaders are a chance vehicle, as far as i'm aware. This means, as such they're not sent as a requirement. You'll have to manually add Operational Team Leader to each of the missions json. This issue doesn't exist in the new version- which should be out soon.

**Comment by jackbayliss** [comment]
Closing due to release of [0.0.9.8](https://github.com/jackbayliss/Mission-Chief-Bot/releases/tag/0.0.9.8) which will rectify this issue.

**Comment by Whitchit** [comment]
This issue has not been resolved, despite downloading and using the latest version mission number 129 is not dispatching OTLs despite it being a mission requirement. 

This version has also broken hospital transports as it is now stating all hospitals are full (they are not in reality anywhere near full capacity or too far away).

**Comment by jackbayliss** [comment]
@Whitchit  Fairly sure it does get despatched, just not with the rest of the vehicles. So, what happens is at first it'll send the known requirements but on the second iteration of the mission (when it turns red) it'll pick up the missing units and send those.

As for the hospital transports, it's the same as 0.0.9.7- if the server response has issues it'll crash the patient transport- thus in theory the bot thinks it has nothing to transport.

**Comment by Whitchit** [comment]
So if the bot thinks it has nothing to transport why does it say hospitals are full?

**Comment by jackbayliss** [comment]
@Whitchit  Sorry, I worded it wrong. It's because it can't find the element on the page- i.e it can't see available hospitals. Then, because of this it thinks all the hospitals are full releasing the patient.

**Comment by Whitchit** [comment]
Gotcha, thanks for clarifying

**Comment by jackbayliss** [comment]
For reference, I've not had any issue transporting: ![image](https://user-images.githubusercontent.com/13621738/86970134-cbe79c00-c166-11ea-8419-17ba0cd23204.png)
