### ISSUE TITLE
Bot dispatch all missions

### ISSUE THREAD

**Issue by nickstop** [jackbayliss/Mission-Chief-Bot#4]
```
# The bot will automatically share EVERY mission it comes across- following the GENERAL settings.
share_all = true
# The min amount of credits a mission must be to be shared
min_share_credit = 2500
# The max amount of credits a mission must be to be shared
max_share_credit = 10000
```

This is my config. But it will share every missions. In my opinion it should only share missions between 2500 cr. and 10000 cr.?

**Comment by jackbayliss** [comment]
The share_all should be false, that will literally share every mission. 

:)

**Comment by nickstop** [comment]
Ok, now it's set to:

# The bot will automatically share EVERY mission it comes across- following the GENERAL settings.
share_all = false
# The min amount of credits a mission must be to be shared
min_share_credit = 2000
# The max amount of credits a mission must be to be shared
max_share_credit = -1

bot it says by each mission that 
`2021-04-20 08:13:57,832 Mission did not meet the min_share_credit, or max_share_credit - not sharing
2021-04-20 08:13:57,832 Mission did not meet the min_share_credit, or max_share_credit - not sharing`

**Comment by jackbayliss** [comment]
Your max share credit shouldn’t be -1, it should be something like 10000 or whatever the max credits you’d like it to share  

>

**Comment by nickstop** [comment]
thx
