### ISSUE TITLE
Problem in Portuguese server

### ISSUE THREAD

**Issue by olle12** [jackbayliss/Mission-Chief-Bot#41]
Hello, the new update is out of date on the Portuguese server.
The vehicles have changed their name and the bot does not recognize it.

If I could see I would appreciate it.

Thanks for listening.

Best regards, olle12

**Comment by jackbayliss** [comment]
Hi @olle12  - let me know which vehicles aren't working and I can take a look. It may be better to message me on Discord- as that way I can ask for ids if there's some missing.

**Comment by olle12** [comment]
Hello
The names that have changed form these: ´
viatura de batalhão - veículo de comando
Caminhão de Bombeiros -  Veículo de Combate a Incêndios
Veículo plataforma - Veículo escada
Veículos de resgate pesado - veiculo de desencarceramento
caminhao pipa - Veiculo Tanque
Veiculo de produtos prigosos - Veículos de Matérias Perigosas

**Comment by jackbayliss** [comment]
@olle12  As far I'm aware the bot still works, the bot reads the missing vehicles and requirements are read as is- so as long as you match them in the links.json and missing.json it should work.

**Comment by olle12** [comment]
Hello, the error that appears is a specific vehicle:
hazardous materials vehicles was not found at links.json - add it or inform the developer

**Comment by jackbayliss** [comment]
@olle12  Ah, I see. This is not an error as such- but it's telling you to add that particular vehicle to the links.json 
so- in this case you'd add "hazardous materials vehicles" : [vehicle_id] to the links.json. Replace `vehicle_id` with the id type of the vehicle.

You may see a few of these, as I don't have a big enough account to test each region :)

**Comment by olle12** [comment]
Ok I'll try to do as you told me
