### ISSUE TITLE
Enable/Disable Transport to Alliance Buildings

### ISSUE THREAD

**Issue by Papanikolis9** [jackbayliss/Mission-Chief-Bot#43]
- I believe that the option to edit the config file and select if you want to use the Hospitals or the Cells of your alliance, would be perfect. It will make the decision and avoid sending your patients or prisoners in Alliance buildings.

- Also the perfect scenario would be if you could select how many prisoners or patients you want to send to your alliance and after that number, they will "leave without transport"

**Reason**
1. With this you will not take the space of your teammates in prisons and hospitals and everyone will share the slots.

2.  This will solve a problem that sometimes if there is a slot too far, the transports will choose it because there isn't another closer slot available. So the transport will take longer, and the credits that your receive are not worth it for the time that is spent.

**Comment by jackbayliss** [comment]
@Papanikolis9 The idea of whether to transport to alliance or not is a good idea to have in the config. But, we'd need to know which hospitals were alliance owned etc. so, I'd need to look if we can get that from the game. 

That being said I'm not very motivated to add new features at the moment with how stable the current version is. I may add a few additions at a later date and release it as a 'pay what you want' for newer versions- that way if you want it free you can use older versions, or you can pay for example £1 - to whatever you want for newer versions that way I can cover my cost of development.
