### ISSUE TITLE
Where can i find the Discord Link

### ISSUE THREAD

**Issue by jaholltzi** [jackbayliss/Mission-Chief-Bot#43]
Hello,
I where can I find the Discord invitation link?

**Comment by jackbayliss** [comment]
You must subscribe via the website, and then you’ll see it :)

**Comment by jaholltzi** [comment]
Ok, is it possible to join the server first and then subscribe to the bot because I would like to ask the user if the bot is good

**Comment by jackbayliss** [comment]
https://discord.gg/H3VUwCMx

**Comment by jaholltzi** [comment]
Thanks
