### ISSUE TITLE
[improvement] Ignore player missions in order to focus on Alliance missions

### ISSUE THREAD

**Issue by ni7roXX** [jackbayliss/Mission-Chief-Bot#44]
Hello, 

Thought to mentioned a new possible improvement here in order to be planned if possible for a future release. 

Now that we have mission ignore for player missions, i`m thinking that an ignore all player missions and close only alliance missions would be a nice upgrade. 

In config this should be an easy set as true, no need to have the same behavior as the skip specific missions on the player side. 

Thanks

**Comment by jackbayliss** [comment]
This will be implemented next patch! I’m currently on Holiday, but as soon as I’m back I’ll be working on the new version: :)

>

**Comment by ni7roXX** [comment]
Top ! thank you, enjoy the Holiday 
     On Monday, August 3, 2020, 11:03:55 AM PDT, Jack <notifications@github.com> wrote:  
 
 

This will be implemented next patch! I’m currently on Holiday, but as soon as I’m back I’ll be working on the new version: :)

>

**Comment by jackbayliss** [comment]
@ni7roXX  This is done my side, will be in next patch :)

**Comment by jackbayliss** [comment]
Live with version 1.1 👍
