### ISSUE TITLE
Generate.Py[ISSUE]

### ISSUE THREAD

**Issue by Esxb** [jackbayliss/Mission-Chief-Bot#45]
When running the command "python3 generate.py" it spills the code and provides a error message. (FREE Version)

**Comment by jackbayliss** [comment]
@Esxb  Apologies for the issue! I'll try and have this fixed once I'm back from Holiday

**Comment by Esxb** [comment]
Not an issue bud, enjoy the holiday!!!

**Comment by jackbayliss** [comment]
@Esxb  Hi mate, apologies for the delay. I had a quick look-  at the moment I need to create a new branch for the free version as I can't edit previous commits etc. 

What I would suggest is download the paid version then the generate.py will work fine then. You'll then need to go back and copy any new missions into a folder of the free one perhaps. Not exactly a fix, but I'll need to do something to fix the free version. Maybe a new branch 👍
