### ISSUE TITLE
[ISSUE]*Could not log you in, perhaps server is F*cked*

### ISSUE THREAD

**Issue by Whitchit** [jackbayliss/Mission-Chief-Bot#46]
The bot is no longer logging me in. This has been an issue now for over 2 weeks. No account details have changed. 

The bot should log me in but it isn't working

Tried on latest free and sponsored versions.

**Comment by jackbayliss** [comment]
@Whitchit  I haven't had any reports! I'd double check your config and ensure the user password and region is correct 👍

**Comment by jackbayliss** [comment]
Just to clarify, I've double checked on a test account and it seems OK see the image below:
![image](https://user-images.githubusercontent.com/13621738/89957588-b49d4200-dc2f-11ea-9bc2-371be63485b9.png)

**Comment by Whitchit** [comment]
Update: The bot tried and failed 30 times to log me in when I left it to run. 31st time was sucessful. Any idea what is causing that?

**Comment by jackbayliss** [comment]
@Whitchit  It's definitely unusual and I've not heard of it before, it could be down to your broadband connection. I would recommend giving it a cool off period for a little while (Give it a couple hours). Out of interest which region are you using? and device?

**Comment by Whitchit** [comment]
UK, Windows 10 Laptop, 50Ghz Average connection speed via ethernet Cat 7+

**Comment by jackbayliss** [comment]
@Whitchit Are you using hard wired Ethernet cable or Wi-Fi? Do you have a firewall etc? 

There could be a number of things affecting it, but nothing has changed in terms of the bot. 

Perhaps try making a different account and seeing if that logs in too. 

I've only seen this kind of thing happen because of a bandwidth restriction- but if you're using a residential network I doubt that would be the case. 

If possible try and use your mobile data (via your phone) to your laptop to rule out network issues.

**Comment by Whitchit** [comment]
I mean the firewall pops up when i start a new version of the bot for the first time, but otherwise does not restrict it. I've not got any  bandwidth restrictions and same issue occurs on my mobile data and neighbour's wifi (with permission)

**Comment by jackbayliss** [comment]
@Whitchit Has this only started occurring recently? Or; has it been like it for awhile? Only thing left is to try a different login and see if that works

**Comment by Whitchit** [comment]
Last few weeks it's been an issue, maybe just over a fortnight ago? I've got 2 other accounts, and the bot has the same issue with them as well. Also tried AU and US servers

**Comment by jackbayliss** [comment]
@Whitchit its awfully strange, are they big accounts that you're using?

I've had 0 reports of any issues logging in which makes me confused; the only other thing you can try is using aws free tier to rule it out being anything computer related.

**Comment by Whitchit** [comment]
Not sure what aws free tier is - and my UK account is pretty big to be fair

**Comment by Whitchit** [comment]
restarted the bot and it worked first time, I know intermittent issues are very hard to diagnose and since it's working again after a restart I'll close this thread for now, pending further issues :)

**Comment by BigBearEvo** [comment]
Sounds odd but the larger the account the more the bot has to work for some reason, I've increased my size in game station wise considerably and its casing mine to not log in first 2-3 times but I've also had recent issues with firewall and Antivirus updates from windows. My US account works perfect, but the UK is still laggy as hell. but it is getting better though.

**Comment by jackbayliss** [comment]
@BigBearEvo Yeah; it's strange- but usually it only takes 3 tries to login rather than completely not logging in at all. I don't think it's an issue as I know there's huge accounts using the bot- but I think this was an isolated incident.
