### ISSUE TITLE
Paid but bot telling me I haven't 

### ISSUE THREAD

**Issue by Letswinthis123** [jackbayliss/Mission-Chief-Bot#48]
So I have the account here on github and have paid for the bot however whenever I load up the bot it tells me I haven't actually paid and am not authorised to use the service?

Help please?

**Comment by jackbayliss** [comment]
@Letswinthis123  Payment is not via Github, use the website in the description.

**Comment by Letswinthis123** [comment]
Cheers but well, the website seems to be having issues for me. Unable to make an account and I have no idea why

**Comment by jackbayliss** [comment]
Try making a new account with new details
