### ISSUE TITLE
crashing issue related to some missing vehicles

### ISSUE THREAD

**Issue by Kulifloerkus** [jackbayliss/Mission-Chief-Bot#48]
Hi,

0.0.9.8.1 is crashing by reading the missing vehicles:

>
> 01/09/2020 16:17:38: Checking Hochwasserschadenslage
> [{'requirement': 'löschfahrzeuge (lf)', 'qty': '25'}, {'requirement': 'drehleiter (dlk 23)', 'qty': '1'}, {'requirement': 'fwk', 'qty': '2'}, {'requirement': 'rüstwagen oder hlf', 'qty': '3'}, {'requirement': 'gerätekraftwagen (gkw)', 'qty': '4'}, {'requirement': 'thw-einsatzleitung (mtw tz)', 'qty': '3'}, {'requirement': 'thw-mehrzweckkraftwagen (mzkw)', 'qty': '3'}, {'requirement': 'schlauchwagen (gw-l2 wasser', 'qty': '7'}, {'requirement': '1000', 'qty': '**SW**'}, {'requirement': '2000 oder ähnliches)', 'qty': '**SW**'}, {'requirement': 'boot', 'qty': '1'}]
>
![Unbenannt](https://user-images.githubusercontent.com/64958878/91989829-47ae3100-ed31-11ea-880c-e7df1b155f6a.PNG)
"Schlauchwagen (GW-L2 Wasser, SW 1000, SW 2000 oder Ähnliches)" is one vehicle. The bot reads a vehicle 1000 and will send it SW-times, but SW is not a number and the bot is crashing.

**Comment by jackbayliss** [comment]
@Kulifloerkus You're correct. This is an issue that's only affecting DE for this select vehicle. Unfortunately the code base for the bot is at premium level so I'm doubtful it'll be fixed for the free version. As I'll have to revert all the changes haha (my bad). I need to work on this for the premium version so I'll need a DE tester for this issue. It's purely with how this particular vehicle is displayed I just need to find a way to handle it.

**Comment by Kulifloerkus** [comment]
I can test this for you.

**Comment by jackbayliss** [comment]
Sure, happy for you to test it- will need you to try and get that vehicle - "Schlauchwagen (GW-L2 Wasser, SW 1000, SW 2000 oder Ähnliches)" if possible- I'll have to manually fix this vehicle 👍🏻

**Comment by Kulifloerkus** [comment]
no problem, I have the vehicle and I can generate the error with a little time

**Comment by jackbayliss** [comment]
Sweet, message me on Discord and we'll get the ball rolling.

**Comment by jackbayliss** [comment]
I believe this is fixed with the newest patch- give it a try and let me know 💯
