### ISSUE TITLE
Missionbot Website

### ISSUE THREAD

**Issue by RBXFFW** [jackbayliss/Mission-Chief-Bot#49]
It's not possible to log in in the Website

**Comment by NotoriousBims** [comment]
I just tested logging in myself and it works ok. Can you explain further what your issue is? 

Better yet, if would be better for you if you joined our discord for the bot. https://discord.gg/6duw38quee

**Comment by RBXFFW** [comment]
The issue was that I used the nickname and not the email

NotoriousBims ***@***.***> schrieb am Sa. 1. Jan. 2022 um
18:44:

**Comment by NotoriousBims** [comment]
So you were able to log in ok then?

**Comment by RBXFFW** [comment]
Yes

NotoriousBims ***@***.***> schrieb am Sa. 1. Jan. 2022 um
18:48:

**Comment by NotoriousBims** [comment]
Sounds good. If you need any further support, join our discord above.
