### ISSUE TITLE
Vehicle IDs

### ISSUE THREAD

**Issue by nickstop** [jackbayliss/Mission-Chief-Bot#5]
Could you Post a list of the vehicle ID. I need it for the alliance function. So that i can Send one vehicle to each Mission.

Thank you

**Comment by jackbayliss** [comment]
You can find them in your json folder, region then links / missing .json. There's no master list sadly - we manually add each vehicle. 

Or, just visit [DOMAIN]/api/vehicles and use the vehicle_type property.
