### ISSUE TITLE
ValueError frozen MissionChiefBot

### ISSUE THREAD

**Issue by Keziake** [jackbayliss/Mission-Chief-Bot#51]
On the french version, I often get this error, occurs mainly with police & fire vehicles.

One example on MissionId 155: 

2022-01-03 10:32:51,741 Found missing vehicles..
`<class 'ValueError'> <frozen MissionChiefBot> 885`

Sometimes I get this one:
2022-01-05 07:15:46,182 Checking Un camion avec une semi-remorque en feu
2022-01-05 07:15:46,601 Found missing vehicles..
`<class 'ValueError'> <frozen MissionChiefBot> 1056`

**Comment by jackbayliss** [comment]
@Saxoprane  This is an issue with the FR version, if you DM me on Discord, I will send you the beta that fixes this.

**Comment by jackbayliss** [comment]
@Keziake Let us know if it works

**Comment by Keziake** [comment]
@jackbayliss It seems to be working ok now. Running for 5 hours and no errors.
Thanks

**Comment by NotoriousBims** [comment]
Can this be closed pending release of new version?

**Comment by jackbayliss** [comment]
@NotoriousBims  I don't see why not, it's a specific issue related to FR, it's not 100% fixed - but it works. Perhaps open one in projects to look at FR specifically
