### ISSUE TITLE
Patient missing text is not splitted by ", "

### ISSUE THREAD

**Issue by meyerdominik** [jackbayliss/Mission-Chief-Bot#52]
**Describe the bug**
Patient missing text is not splitted by ", "

**Expected behaviour**
The Vehicles rtw and nef from the missing.json should be dispatched

**Screenshots**
[Screenshot](https://prnt.sc/uj3rdl)

**Bot version and region**
Current version on de servers

**Comment by jackbayliss** [comment]
I'll get working on patching this and send you a test.

**Comment by jackbayliss** [comment]
This is fixed as of today! Sorry for the delay- will be in the next upcoming release.

**Comment by meyerdominik** [comment]
Works! See [Screenshot](http://prntscr.com/v7o52l)

Ty @jackbayliss
