### ISSUE TITLE
Normal missing text is not finding a single vehicle

### ISSUE THREAD

**Issue by meyerdominik** [jackbayliss/Mission-Chief-Bot#53]
**Describe the bug**
Bot found the missing text but was not able to just dispatch the one vehicle? It tries to send the full requirements!

**Expected behaviour**
Dispatch the one elw 1

**Screenshots**
[Screenshot](https://prnt.sc/uj3wou)

** Bot version and region **
Current version on de servers

**Comment by jackbayliss** [comment]
It's only trying to resend two vehicles, hence the two sleeps. I think again, this particular missing text is confusing it.

**Comment by meyerdominik** [comment]
Can I do something to fix this or is that entirely on your side @jackbayliss ?

**Comment by jackbayliss** [comment]
@meyerdominik  I'll have to send you a debug version for DE so we can see

**Comment by jackbayliss** [comment]
Not able to replicate it on my side yet! Have a DE user trying to replicate the text.

**Comment by jackbayliss** [comment]
@meyerdominik  Can you test the newest version? I believe this should be fixed. Feel free to re-open if it's not- sorry it took so long! 👍🏻

**Comment by meyerdominik** [comment]
@jackbayliss Doesn't work :/ See [Screenshot](http://prntscr.com/v7moi3)

Version 0.1.5
Nothing gets dispatched even though it said so

**Comment by jackbayliss** [comment]
Looks like it found two, hence the two sleeps!

If you can replicate this one I can fix it :)

**Comment by meyerdominik** [comment]
Yes I can replicate it. Let's chat this evening via discord. I'll prepare a mission for you and you can check 👍

**Comment by jackbayliss** [comment]
Closing as I believe we fixed this?

**Comment by meyerdominik** [comment]
yes :)
