### ISSUE TITLE
Issue with the payment

### ISSUE THREAD

**Issue by jjs0002** [jackbayliss/Mission-Chief-Bot#55]
Hello I tried buying the bot on the website and it says the payment was succesful, but nothing happens.

**Comment by jackbayliss** [comment]
Email me your email etc and I can look and activate it

**Comment by jjs0002** [comment]
Thanks for the fast ReplyMy email is ***@***.*** and the username is jjs.FIY i tired it 2 or 3 times because at first I thougt I put in the wrong CreditCard Information. Gesendet von Mail für Windows Von: JackGesendet: Freitag, 11. Februar 2022 14:11An: jackbayliss/Mission-Chief-BotCc: jjs0002; AuthorBetreff: Re: [jackbayliss/Mission-Chief-Bot] Issue with the payment (Issue #55) Email me your email etc and I can look and activate it Sent from my iPhone> On 11 Feb 2022, at 12:58, jjs0002 ***@***.***> wrote:> > ﻿> Hello I tried buying the bot on the website and it says the payment was succesful, but nothing happens.> > —> Reply to this email directly, view it on GitHub, or unsubscribe.> You are receiving this because you are subscribed to this thread.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jackbayliss** [comment]
It is now enabled! Try now

**Comment by jjs0002** [comment]
Hmm still doesnt work Gesendet von Mail für Windows Von: JackGesendet: Freitag, 11. Februar 2022 14:17An: jackbayliss/Mission-Chief-BotCc: jjs0002; AuthorBetreff: Re: [jackbayliss/Mission-Chief-Bot] Issue with the payment (Issue #55) It is now enabled! Try now Sent from my iPhone> On 11 Feb 2022, at 13:15, jjs0002 ***@***.***> wrote:> > ﻿> Thanks for the fast ReplyMy email is ***@***.*** and the username is jjs.FIY i tired it 2 or 3 times because at first I thougt I put in the wrong CreditCard Information. Gesendet von Mail für Windows Von: JackGesendet: Freitag, 11. Februar 2022 14:11An: jackbayliss/Mission-Chief-BotCc: jjs0002; AuthorBetreff: Re: [jackbayliss/Mission-Chief-Bot] Issue with the payment (Issue #55) Email me your email etc and I can look and activate it Sent from my iPhone> On 11 Feb 2022, at 12:58, jjs0002 ***@***.***> wrote:> > ﻿> Hello I tried buying the bot on the website and it says the payment was succesful, but nothing happens.> > —> Reply to this email directly, view it on GitHub, or unsubscribe.> You are receiving this because you are subscribed to this thread.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***> > —> Reply to this email directly, view it on GitHub, or unsubscribe.> You are receiving this because you commented.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jackbayliss** [comment]
You need to go into the website, click add user then add your username

**Comment by jjs0002** [comment]
Yes I get that, but it doesn´t Show up. Gesendet von Mail für Windows Von: JackGesendet: Freitag, 11. Februar 2022 14:38An: jackbayliss/Mission-Chief-BotCc: jjs0002; AuthorBetreff: Re: [jackbayliss/Mission-Chief-Bot] Issue with the payment (Issue #55) You need to go into the website, click add user then add your username—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jackbayliss** [comment]
Logout and back in?

**Comment by jjs0002** [comment]
Nope. Tried it multiple times now. Tried it also with my mobile. Gesendet von Mail für Windows Von: JackGesendet: Freitag, 11. Februar 2022 14:53An: jackbayliss/Mission-Chief-BotCc: jjs0002; AuthorBetreff: Re: [jackbayliss/Mission-Chief-Bot] Issue with the payment (Issue #55) Logout and back in?Sent from my iPhone> On 11 Feb 2022, at 13:43, jjs0002 ***@***.***> wrote:> > ﻿> Yes I get that, but it doesn´t Show up. Gesendet von Mail für Windows Von: JackGesendet: Freitag, 11. Februar 2022 14:38An: jackbayliss/Mission-Chief-BotCc: jjs0002; AuthorBetreff: Re: [jackbayliss/Mission-Chief-Bot] Issue with the payment (Issue #55) You need to go into the website, click add user then add your username—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***> > —> Reply to this email directly, view it on GitHub, or unsubscribe.> You are receiving this because you commented.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jackbayliss** [comment]
https://discord.gg/UG7KXcrH
