### ISSUE TITLE
Paid but no access

### ISSUE THREAD

**Issue by spull1s** [jackbayliss/Mission-Chief-Bot#56]
Hi, Ive sent the payment but no change on website, so cant access unfortunately

**Comment by jackbayliss** [comment]
Email me the email you use on the site

**Comment by spull1s** [comment]
Hi, its this one im writing from so

***@***.***



Den lör 12 feb. 2022 kl 08:27 skrev Jack ***@***.***>:

> Email me the email you use on the site
>
> Sent from my iPhone
>

**Comment by jackbayliss** [comment]
Can you email it me? Check on my GitHub. Profile for my email :)
