### ISSUE TITLE
 Registration problem

### ISSUE THREAD

**Issue by Wolfwarrior69** [jackbayliss/Mission-Chief-Bot#57]
Hello. I paid for a subscription on the website. I have not received access to the discord or confirmation by e-mail that the transaction was successful. Where can I find the option to unsubscribe or verify transaction ?

**Comment by jackbayliss** [comment]
@Wolfwarrior69  Did you fix this?

**Comment by Dudzik93** [comment]
Hello, 
I have the same problem like Wolfwarrior.
I finish of registry, i was paid. 
But i do not have any mail and no have a acces to bot.

**Comment by Dudzik93** [comment]
@Wolfwarrior69 

I have the same problem. Could you tell me how i can repaire it?

**Comment by jackbayliss** [comment]
@Dudzik93  https://discord.gg/E5hEpHqF
Please email me, I can activate you :)

**Comment by jackbayliss** [comment]
@Dudzik93  Discord is here : https://discord.gg/urbhGKbr

Please email me if you're having issues
