### ISSUE TITLE
Registering

### ISSUE THREAD

**Issue by robloxrainy** [jackbayliss/Mission-Chief-Bot#58]
Hello, I can't register on the wesbite, It don't go anywhere when I click on the £1 Subscription

**Comment by jackbayliss** [comment]
@robloxrainy  You need to register, login- go to dashboard, then pricing- then pay.

**Comment by robloxrainy** [comment]
@jackbayliss  I have it don't load it, got a discord that I could show you it on.

**Comment by jackbayliss** [comment]
@robloxrainy 

https://discord.gg/CCNXtA5s
