### ISSUE TITLE
Missing vehicle

### ISSUE THREAD

**Issue by Sketchy28** [jackbayliss/Mission-Chief-Bot#58]
The system doesn’t send vehicles to .au missions burning machine or monoxide poisoning.
I thought I saw these missions in code.
Comes up as missing vehicle and says add it to missing .json. Can you explain how to add.
Australian server

**Comment by jackbayliss** [comment]
Post a screenshot of the red text, it’s easier to explain it that way :)

**Comment by jackbayliss** [comment]
@Sketchy28

**Comment by MC-bot-test** [comment]
The only unit that is common to both is the Rescue one

Make sure both your au links.json and missing.json contain the following lines

"major rescue vehicle": [4],
"rescue": [4],

**Comment by Sketchy28** [comment]
Thanks mat

**Comment by jackbayliss** [comment]
Closing thanks @MC-bot-test
