### ISSUE TITLE
GW-Taucher not used in german version

### ISSUE THREAD

**Issue by argentinia1** [jackbayliss/Mission-Chief-Bot#59]
Hey there,
i recognized that in german version the TKW (Tauchkraftwagen/vehicle ID 69 - same as GW-Taucher in fire deparments) of the technical aid organization ist not used in water rescue operations. In germany there are several units who can alarm water rescue units. But this one isn't used in the script yet. Please add this to the alarm list. Thanks

**Comment by jackbayliss** [comment]
@argentinia1  Please join Discord so I can help further : https://discord.gg/H55ra8fR
