### ISSUE TITLE
Free version gone?

### ISSUE THREAD

**Issue by Fogest** [jackbayliss/Mission-Chief-Bot#59]
Hey, the links on your projects to the free version don't seem to work and it seems to be because the tagged free version no longer exists. Is there a reason for this?

**Comment by jackbayliss** [comment]
@Fogest 
The free version was removed purely to stop abuse, it had over 1k downloads and had no way of being monitored etc. Which entails heavy usage on the mission chief servers. A lot of communities were complaining about botters etc. So, to stop any unwanted attention from the devs I decided to make it a premium, at the rate of $1 a month, therefore making it a smaller user amount and keeping it maintainable.

**Comment by Fogest** [comment]
I guess I can respect that decision though I think the documentation should be updated to reflect there is no longer a free version as there were quite a few places that link to the free download which is now a 404.

**Comment by jackbayliss** [comment]
No problem, I need to edit the README to be honest 💯

**Comment by Fogest** [comment]
Haha I feel like documentation is always an area that slips for me. As a side note I sent you an email :)

**Comment by jackbayliss** [comment]
@Fogest  Responded :)

**Comment by Fogest** [comment]
@jackbayliss Ah I see, Gmail got a bit overzealous and sent your replies to my spam folder. Quite odd that it went to my spam folder despite me having originally emailed you first.

![image](https://user-images.githubusercontent.com/1163628/95382828-3e782d00-08b8-11eb-9148-8b7232ffefe5.png)
