### ISSUE TITLE
Share_own_send_1 Options

### ISSUE THREAD

**Issue by NotoriousBims** [jackbayliss/Mission-Chief-Bot#60]
The options would be something like:

Alliance share:
Share own missions and send 1 required unit: true/false
Share own mission min credit: ######
share own mission max credit: #######
Share own mission send required ambulances (ems chief too): true/false
Share own mission time limit: 0-48 hours (bot will close mission inside this time limit by sending rest of missing units)

Optional:
Share overwrite:
Share own mission unit overwrite: (vehicle IDs)
Share own mission overwrite qty: ###

This will instead of sending any required unit, it will send the specified number of vehicles based on the vehicle ID.

For example:

Alliance share:
Share own missions and send 1 required unit: true
Share own mission min credit: 3999
share own mission max credit: 35000
Share own mission send required ambulances (ems chief too): true
Share own mission time limit: 6

So if a mission is 6000 credits, with 8 patients, the bot will share the mission, dispatch the closest required unit, dispatch 8 ambulances. Once the mission is open for 6 hours, the bot will send whatever is read in the missing text and close the call.

_Originally posted by @NotoriousBims in https://github.com/jackbayliss/Mission-Chief-Bot/issues/19#issuecomment-1008424700_

**Comment by NotoriousBims** [comment]
Above comment is referencing original share_own_send_1 option

This issue will be regarding updates to that function when possible. 

-Add

Sending EMS chief (US region but make work for other regions too) if patient count is above 10
Mission time limits. Bot will send the rest of the units to complete a shared mission at the end of a set time limit
Unit overwrite: Bot sends a required unit for the mission, allow user to enter vehicle ID of a unit to overwrite

**Comment by jackbayliss** [comment]
Done
