### ISSUE TITLE
bot sending Ambulances to mission where is already done was awaiting for other user to send their patient

### ISSUE THREAD

**Issue by JoshuaBilboe96** [jackbayliss/Mission-Chief-Bot#60]
I noticed that the bot sending Ambulances to mission where is already done was awaiting for other user to send their patient to the hospital
is there any way to fix this issue?

**Comment by JoshuaBilboe96** [comment]
i have attached the screenshot to show you what i mean :) 

![Screenshot_6](https://user-images.githubusercontent.com/47194625/95321055-62c11300-0892-11eb-8071-8ce6d22a7b05.png)

**Comment by jackbayliss** [comment]
You can disable alliance missions, I believe this is because it's an alliance mission- perhaps add the name / id to your ignore list.

**Comment by JoshuaBilboe96** [comment]
yes you are right its only on alliance missions but they get alot more money than own missons where no one else can see and how i can see my ignore list?

**Comment by Sketchy28** [comment]
Sketchy28 im not added to game
