### ISSUE TITLE
[ISSUE] DE Links and Missing fix

### ISSUE THREAD

**Issue by Stiker839** [jackbayliss/Mission-Chief-Bot#61]
**Describe the bug**
Some units are missing from the DE version and lead to some missions being stuck.

** Bot version and region **
Please let us know which region, and which bot version you're using.

Sponsor and DE

**Additional context**
N/A

**Comment by jackbayliss** [comment]
They'll need to be added by a DE user, then should work?

**Comment by jackbayliss** [comment]
Closing as no response, ask in the Discord if it still happens.
