### ISSUE TITLE
Issue when specific water amount is required

### ISSUE THREAD

**Issue by thejockel** [jackbayliss/Mission-Chief-Bot#61]
Hey,
when a mission requires a specific amount of water the bot only add a single vehicle.
Therefore the mission can't complete.  

![image](https://user-images.githubusercontent.com/12292135/161294487-cdf7e81a-e456-44d2-a975-db7495e059c5.png)

```
2022-04-01 15:17:20,477 1 missions found
2022-04-01 15:17:20,482 Checking Mittlerer Feldbrand
2022-04-01 15:17:22,824 mapper found 'Zusätzlich benötigte Fahrzeuge' and 'l. Wasser' in missing text, forcing löschfahrzeuge
```

THX Jockel

**Comment by thejockel** [comment]
![image](https://user-images.githubusercontent.com/12292135/161298093-5cce36a8-b23d-4fea-a0e5-dba46787ba62.png)

Here an other example.

**Comment by jackbayliss** [comment]
You can use the terms.json to fix this, you can remove that entry from the mapper, if you create a ticket via Discord I can walk you through it On 1 Apr 2022 16:49, thejockel ***@***.***> wrote:

Here an other example.
