### ISSUE TITLE
Add User issue

### ISSUE THREAD

**Issue by DjBiskas** [jackbayliss/Mission-Chief-Bot#62]
Hi, i'm having problems with the "add user" function on MCBot. I put the user name and country, but it's stuck. Can you help me?

**Comment by jackbayliss** [comment]
Try now :)On 17 Apr 2022 16:13, DjBiskas ***@***.***> wrote:
Hi, i'm having problems with the "add user" function on MCBot. I put the user name and country, but it's stuck. Can you help me?

**Comment by DjBiskas** [comment]
Done. Thnx...
