### ISSUE TITLE
Issues Registering

### ISSUE THREAD

**Issue by athens-networking** [jackbayliss/Mission-Chief-Bot#65]
I attempted to register and it says user created but then brings me to the landing page and doesn't log me in when I try to

**Comment by jackbayliss** [comment]
Notice that the login page asks for emailOn 29 Apr 2022 05:37, athens-networking ***@***.***> wrote:
I attempted to register and it says user created but then brings me to the landing page and doesn't log me in when I try to

**Comment by jackbayliss** [comment]
Ensure to login via email, not username.
