### ISSUE TITLE
[ISSUE] Bot shutting down with auto_hire sets to true

### ISSUE THREAD

**Issue by squoll** [jackbayliss/Mission-Chief-Bot#66]
**Describe the bug**
Bot is shutting down when you set in config.ini auto_hire to true after 3 days. If you set it to off than bot runs as usual.

**Screenshots**
![s](https://user-images.githubusercontent.com/9107509/96361220-97ec2180-112c-11eb-8ac8-a76550ee83fc.PNG)

# Bot version and region 

0.1.4
**Region**: *ru*

**Debug File**
[debug.txt](https://github.com/jackbayliss/Mission-Chief-Bot/files/5397162/debug.txt)

**Comment by jackbayliss** [comment]
Is there a laststarted.json in your json folder? If so try and remove it.

>

**Comment by Fogest** [comment]
This looks like the same problem I reported in #63 . Deleting the file mentioned does fix the problem temporarily though it does seem to recur at a later date. So that fix mentioned over on that issue will be helpful still :)

**Comment by jackbayliss** [comment]
@squoll  As fogest mentioned, this is a known issue- will hopefully be patched next release. Just need to get round to it!

Feel free to re-open if it's not fixed.

**Comment by jackbayliss** [comment]
This was patched a long time ago by the way!
