### ISSUE TITLE
Bot issue

### ISSUE THREAD

**Issue by mlande5** [jackbayliss/Mission-Chief-Bot#68]
Starting yesterday, I noticed that the bot has been slow seems like it is hanging. 

I've noticed that I see data chunk error messages and another message saying the 
Server may have shite itself - issue with data.

I didn't see any updates to the bot or anyone reporting the issue. 

Any suggestions? 

Thank you 

Mike

**Comment by jackbayliss** [comment]
Hi Mike,This is usually related to internet and the connection between you and the site failing.If you're connected via WiFi I would recommend using a ethernet cable. If it still happens let me know the region 😁On 2 Jun 2022 06:13, mlande5 ***@***.***> wrote:
Starting yesterday, I noticed that the bot has been slow seems like it is hanging.
I've noticed that I see data chunk error messages and another message saying the
Server may have shite itself - issue with data.
I didn't see any updates to the bot or anyone reporting the issue.
Any suggestions?
Thank you
Mike

**Comment by mlande5** [comment]
Hi Jack, 

I'm on an Ethernet connection. So, I looked at my connection between my ISP and MissionChiefbot at  104.21.61.226 it's rock solid not a single dropped back in 500 packets sent. 

I then looked at my ISP to MissionChief and see the same old problem I've been complaining to MissionChief about their connection between NY and Germany has about a 75% packet lost.  So, its weird as the bot hasn't shown this problem before. But I can see how having this loss would cause issues. 

I did add some of the additional messages from the log. 

Thank you Mike

Here are some of the messages I'm seeing. 

caught
<class 'requests.exceptions.ConnectionError'> <frozen MissionChiefBot> 301
Server is having issues.. ChunkedEncodingError
<class 'requests.exceptions.ReadTimeout'> <frozen MissionChiefBot> 1117
2022-06-02 02:45:45,035 [UPDATE] Checking your json files for updates...
2022-06-02 02:45:45,042 [UPDATE] Hold tight...
caught
<class 'requests.exceptions.ConnectionError'> <frozen MissionChiefBot> 301
Server may have shite itself - issue with data.
<class 'TypeError'> <frozen MissionChiefBot> 1204

**Comment by jackbayliss** [comment]
@mlande It seems from the log there's a connection timeout / error encoding. This to me would suggest there's some kind of issue occuring.

If you ever need to test the bots connection you can visit : [this url](https://missionchiefbot.com/api/region/uk/missionfiles, if you cant see it or get an error there's some kind of connection issue between you and the bot.

**Comment by jackbayliss** [comment]
Only other suggestion I can suggest is trying it from an alternative location via  VPS etc, if the same occurs I'm happy to take a look further 👍🏻

**Comment by jackbayliss** [comment]
@mlande5  What errors are you getting?
