### ISSUE TITLE
[Feature] Respect Dispatch Center max alliance mission distance

### ISSUE THREAD

**Issue by Fogest** [jackbayliss/Mission-Chief-Bot#68]
Hello,

I have a rather small radius set in my dispatch center for alliance missions. It is only at 50 km. When I look at my list on MC I only have at most a few alliance missions I typically see. However the bot seems to see a different set and will be going through many more than these few missions and dispatching units to places farther than 50km. 

If if cannot read from the dispatch center to account for this can this be a configurable thing? Basically an option to define how far units will go for alliance missions.

**Comment by jackbayliss** [comment]
This is something I'd have to look at- the bot technically doesn't read from a despatch centre as it uses "other methods" in order to read the mission data. If I can find a way to limit it I'll definitely implement this. Leave it with me, I'll need to investigate :)

**Comment by Fogest** [comment]
Awesome, thanks :). Especially as a newer player it is hard to have units that are gone for hours as some types of unit I only have a few of so far.

**Comment by jackbayliss** [comment]
@Fogest I've finally got round to doing this properly! The newest update is where it'll be when it's released.

Thanks for the idea, and patience 👍🏻 

Closing, but feel to reply if I messed something :)

``
# Sets max distance that the vehicles will be despatched from, from the mission , 0 = none
max_dispatch_km = 0
``

This will be set for all missions, so hopefully prevent hour-long drives!

**Comment by Fogest** [comment]
This is awesome, thanks! 

I have taken a small break from the game but will be back to it soon. When I come back I will resub using the website instead of Github. 

Out of curiosity what is the best way to handle regenerating missions? On the NA version at least there are a couple new missions added every Monday and it means pretty often the script would break until I ran the generate missions. Is there a good way that people account for this? I am thinking about running a cronjob at some point on Monday's that triggers the generate missions script but wondering if there is a better way?

**Comment by jackbayliss** [comment]
@Fogest  No problem man, take as long as you need.  Usually yeah cronjob for each week. I'm writing a separate script to auto pull request the new missions so hopefully, it'll just be a case of pulling the repo.  

Ideally, I'd just want the bot to auto-update when there are new files, but we're half way there if I can get this auto-update mission script working 👍🏻
