### ISSUE TITLE
[Bug] Bot keeps redispatching more units to shared missions despite already fulfilling the requirements

### ISSUE THREAD

**Issue by Fogest** [jackbayliss/Mission-Chief-Bot#69]
**Describe the bug**
Even though the mission has been shared, the bot still comes back and checks on the mission and will dispatch again units that have requirements already met. For example look in the screenshot. You will see this mission requires 2 police cars and 1 sheriff. I currently have 0 sheriffs finished training and as such I need an alliance mate to come help with this mission. However when the bot looks at the request again it will often dispatch the requirements I do meet again.

I believe this typically happens when the mission is in a **red** status indicating a missing unit. In this case "1x sheriff" is missing. 

**Expected behaviour**
Bot sees that there are already 2 police cars and does not send 2 more repeatedly. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1163628/97122131-db7cf780-16f9-11eb-89a9-43470f0a5bca.png)

** Bot version and region **
0.1.5 US

**Additional context**
It continues to do this as long as I have units. If I had another pair of 2 police cars free it would have also sent those on the bots next pass through.

**Comment by Fogest** [comment]
I got a special issue number 🥇

**Comment by jackbayliss** [comment]
Yeah- this definitely shouldn't happen. I believe it's because it effectively keeps sharing the mission. One way I can fix this is simply-- if the mission is shared, don't touch it again.

**Comment by Fogest** [comment]
Yeah that would be awesome if it didn't keep getting re-shared and re-dispatched <3

**Comment by jackbayliss** [comment]
Will fix it this weekend 👍🏻

**Comment by Fogest** [comment]
Amazing, would love to reenable the mission sharing :).

**Comment by jackbayliss** [comment]
I'm on this, I promise. It'll be in next patch-- just spam me tomorrow so I don't forget 🥇

**Comment by Fogest** [comment]
Here is spam message number 1 ;)

**Comment by Fogest** [comment]
Spam #2 incoming ;)

**Comment by jackbayliss** [comment]
@Fogest  I'm here! After re-looking I believe it's because the Sherriff car was never despatched- so upon failure it just keeps resending. I need to checkout what's happening exactly here so bear with me 🔢

**Comment by Fogest** [comment]
Yeah you may be right. I have had more cases where it happens. I come on
and check after having it run for the night and see a huge chunk of my
units on a single call.

It seems to happen when a unit is dispatched but there is an error when
they are dispatched. For example when the vehicle is not staffed with
qualified members. The bot sees the unit and dispatches them and keeps
doing it again and again. I am sometimes dumb and create units that don't
have the proper trained staff and run into this issue :/

**Comment by jackbayliss** [comment]
Hmm, I could set a config option to basically stop missions from being redespatched once initially done. Tbh I remember writing an on scene and on route reader- so it should know not to keep re-sending. I'll have to recheck it.

**Comment by Fogest** [comment]
Yeah there are a couple options I think. You could check and ensure the dispatch was successful because it does trigger an error message when you try and dispatch a vehicle that does not meet the requirements. Then maybe you just ignore that mission or try and dispatch the next available unit instead of trying that same one again. I'm not sure if that is too complicated as you would need to track each failed vehicle per mission but maybe it isn't too bad?

Or I guess you could also just do similar to what you mentioned and ignore it after the first dispatch. The mission will keep showing as having a "missing" unit so I guess you'd need to ignore that?

**Comment by Fogest** [comment]
I saw in the sponsor update mentioning you're working on only dispatching once to shared alliance missions. I think that the bot should still look at these missions again though because sometimes you have the missing unit clear up and it would be good to fill the mission rather than wait for an alliance member to complete the mission.

**Comment by jackbayliss** [comment]
@Fogest  I think I just need to check the code for on route and on scene so that whatevers in there is subtracted from the amount required- I just need a way of forcing a mission to check it 👍🏻

**Comment by Fogest** [comment]
Yeah I think that would work quite well!

I wonder if you could track the mission in memory that you identify as
being shared to alliance and not having all the units? And then you'd be
able to know to keep checking those. But I'm not sure how the bots code
works and if that is doable or not.

**Comment by jackbayliss** [comment]
Definitely doable, but not sure how Python handles things in memory over a long period of time- not sure if missionchief re-use the same mission id's after so long too. So, may be easier to have it quickly check each time

**Comment by Fogest** [comment]
Yeah I guess a lot of unknowns. I assume just some simple array of IDs
shouldn't have a probably staying in memory. I can't see that memory being
cleared from a running program.

But yeah that would definitely have some problems if IDs are reused
especially if they are reused shortly after.

If a quick check though doesn't take too long and doesn't need too huge of
a cool down between those checks then it may be a safer option. Just if it
takes awhile to check and someone has a lot of missions it may slow down
getting to new missions

**Comment by jackbayliss** [comment]
I believe this is sorted in the newest release-- may have to re-open this if not. I created an array to store the missionId and mission type, so that if they're both the same it won't keep re-alerting the alliance despatch. (This issue should occur on auto share mission), re open or drop me a Discord message if it still occurs.
