### ISSUE TITLE
Vehicle ID's

### ISSUE THREAD

**Issue by nickstop** [jackbayliss/Mission-Chief-Bot#7]
Hey, in my missing.json is missing the Rettungstreppen vehicle id and FLF id.

Im from germany de

**Comment by jackbayliss** [comment]
@nickstop  Hi! You can add them simply by doing "Rettungstreppen" :[ID] and "FLF" : [ID] 

You can find the id via /api/vehicle and looking for vehicle_type 👍🏻

**Comment by tobst96** [comment]
It's now okay. Can you close.

Habe gerade ein Request gestartet um eine neue Missing.json ein zu spielen. Da wurde vieles optimiert. Wenn da was fehlt, einfach über Discord schreiben. Dann ändere ich es.
