### ISSUE TITLE
UK version Armed Response not sent to High-Risk Warrant. 

### ISSUE THREAD

**Issue by Lew045** [jackbayliss/Mission-Chief-Bot#7]
It said to either edit the .json file or contact a moderator

**Comment by jackbayliss** [comment]
I'm presuming the armed response personnel was missing? If possible please attach your file.

**Comment by Lew045** [comment]
No I have many Armed Response available. Which file would you like attaching?

**Comment by Stiker839** [comment]
We are working on a fix for this, for the time being go to the mission json file and replace the file there with this one :)

https://we.tl/t-xiDSAHvqOV

**Comment by jackbayliss** [comment]
@Lew045  As above, you'll have to manually update the mission file. But this should be fully fixed in the next patch.
