### ISSUE TITLE
The bot doesn't send any ambulances to hospitals

### ISSUE THREAD

**Issue by Doki83** [jackbayliss/Mission-Chief-Bot#71]
**Describe the bug**
I have started the bot, it ist functioning good, but it doesn't solve the transport requests. I have to do it every time myself.
Is it normal or a bug?

** Bot version and region **
US Version, 0.1.5

**Comment by Doki83** [comment]
I haven't found anything about it in the config.ini

**Comment by jackbayliss** [comment]
It’ll solve the transports once your batch has been run!

So, at the end of your batch they should get picked up :)

>

**Comment by jackbayliss** [comment]
@Doki83

**Comment by Doki83** [comment]
Yes, it is funktioning now
