### ISSUE TITLE
Forestry expansion not found?

### ISSUE THREAD

**Issue by Fogest** [jackbayliss/Mission-Chief-Bot#72]
I am getting the following error:
```
04/11/2020 01:39:32: forestry expansions was not found in the links.json - add it or tell a developer :)
```

I am a bit confused what is the problem though. When I look in links.json I see the wildland fire engines. I currently have all type 7 engines for wildland. The links file have the type 7 engine and that type 7 engine (\#32) is in the "wildland fire engines" array. So I am a bit confused what the issue is. Do I need to do something to get this to work?

Here is an image of my links.json:

![image](https://user-images.githubusercontent.com/1163628/98059344-dc5a0b80-1e14-11eb-9ae2-85cd6b433249.png)

**Comment by Fogest** [comment]
I just realized I am stupid and was actually using type 4 engines. Is there a reason the type 4 engine wouldn't be on there? I just want to make sure there isn't something I haven't learned about missionchief's forest expansion yet.

**Comment by BigBearEvo** [comment]
This came up for me, totally random, easy fix, added forestry expansion + unit numbers into the links, done. It's down to not all fire stations having the forestry expansion in that area

**Comment by Fogest** [comment]
@BigBearEvo Can you give me an example of what you mean to do?

**Comment by BigBearEvo** [comment]
![image](https://user-images.githubusercontent.com/1572161/98077115-806ca280-1e67-11eb-8cce-028b6280651e.png)

**Comment by BigBearEvo** [comment]
I have no idea why MC changes its coding or things, i know, i just have to adjust and add what ever it wants to keep it going

**Comment by Fogest** [comment]
Thanks I wasn't sure if you literally meant to add "forestry expansions" as a vehicle in the file so that clears things up. I have added it now and will have to wait for a forestry expansion mission to see if it resolves it :)

**Comment by jackbayliss** [comment]
Closing as it seems related to units- anything mentioned that needs to be added to missing / links will be displayed in red. Just copy it until the ',' and then that's your unit you need to add
