### ISSUE TITLE
EMS Request only for my hospitals

### ISSUE THREAD

**Issue by Doki83** [jackbayliss/Mission-Chief-Bot#74]
Hi!

Is there any possibility to set the following option? I have 8 hospitals and the nearest alliance hospital is 200km away. I want to set, that my ALS Ambulances transport patients only into my hospitals.

Can I do that?

Thx

**Comment by jackbayliss** [comment]
@Doki83  This should already be the case, it should transport to your hospitals before selecting Alliance ones. Unless you mean, it'll only transport to yours? So that, when you're full it will ignore alliance?

**Comment by Doki83** [comment]
Yeah, I mean that, that only into my hospitals.

These are my settings in config.ini:
[GENERAL]
# Just show the players missions, ignore alliance- set true if you want to ignore alliance false will show own missions and alliance.
show_own = true
# Just show alliance missions ignore player missions
just_alliance = false
# The amount of missions to do per execution. It'll only build what you set, so if you have 100 missions and set this to 50- it'll only do 50.
min_missions_per_run = 12
max_missions_per_run = 20
# The bot will attempt to hire staff for all your buildings every set days (below) - if you set this to true
hire_staff = false
# The amount of days it will wait before hiring staff for the allocated amount of days (1,2,3)
hire_staff_days = 1
# The bot will self close when earning over this earning limit- set to 0 for ignore.
earning_limit = 0
# Auto share mission if missing units
auto_share_missing = false
# Sets ambulances to qty to the one found, not the requirements one
ambulancesreal = true
[TIMINGS]
# Sleep interval is how long it sleeps between each despatch, set the min and max- the bot will then select a random time between the two. (WARNING: Make sure you set this to something realistic I.E 6-10 seconds) or you'll essentially DDOS the server- and you will get banned.
min_sleep_interval = 1
max_sleep_interval = 5
# The amount of time it sleeps before continuing to run again. Be reasonable - set the min and max- the bot will then select a random time between the two. :)
min_sleep_per_batch = 1
max_sleep_per_batch = 20
# The amount of time it will sleep per vehicle selection - set the min and max- the bot will then select a random time between the two. :)
min_sleep_per_select= 1
max_sleep_per_select = 2
# Auto shutdown after X seconds - 0 means it'll ignore it.
shutdown_after_seconds = 0
[GENERATE]
grab_only_new = false

I don't want to use any alliance hospitals, the nearest is 200-300km away from my stations.

**Comment by jackbayliss** [comment]
Yes- it's possible. I will have to create a config option for such option.
