### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by JoshuaBilboe96** [jackbayliss/Mission-Chief-Bot#78]
** Bot version and region **
Please let us know which region, and which bot version you're using.
UK / 1.
**Additional context**
Is it possible to have the bot automatically shared to the alliance after dispatch the vehicles?

**Comment by jackbayliss** [comment]
Possible, although I won't be working on new features for awhile. So, expect a delayed release.

**Comment by JoshuaBilboe96** [comment]
Thank you

**Comment by jackbayliss** [comment]
This is technically added in the newest upcoming patch - so for now I am closing :)
