### ISSUE TITLE
Australian Vehicle Update.

### ISSUE THREAD

**Issue by Sketchy28** [jackbayliss/Mission-Chief-Bot#79]
I have missing vehicles and it says to add them to missing.json
How can i do this. i have missions come up still it doesnt start them as i believe they are missing. i have used the generator many times.

**Comment by jackbayliss** [comment]
You'll need to update the list of vehicles in your missing.json.

When you see the error, copy the vehicle name to your missing.json. Then, visit the missionchief website so for example missionchief-australia.com. Visit the /api/vehicles route. When you're there, find the vehicle that matches with the missing text; and look for the vehicle_type of that vehicle. Simply add that to the vehicle, then you're up to date. If you ask in Discord, one of the moderators will sort you out 👍🏻
