### ISSUE TITLE
Found Missing Vehicle 

### ISSUE THREAD

**Issue by mlande5** [jackbayliss/Mission-Chief-Bot#79]
Hi Jack, 

Question, I've downloaded the latest version of the Mission Chief Bot. I'm noticing a message that is appearing a lot and causing a lot of my missions to not run.  

2022-07-30 15:36:12,161 Found missing vehicle coastal helicopters educated personnel, but can't see it in missing.json add it with the vehicle type and it'll work
2022-07-30 15:36:12,380 Mission Deep Water Search & Rescue missing ambulance x 1
2022-07-30 15:36:12,380 Mission Deep Water Search & Rescue missing ambulance x 1

So, if I go to my directory where Mission Bot is stored and go thru the folders to json folder open that up I see 6 json files and another folder called region I open that and select US as that is where I'm at. I now see missions folder, 4 json files. 

I know that the Missions folder holds all the missions that can be dispatched. So, I don't need to go there. 

\Mission-Chief-Bot-main\json\region\us  I go to links.json I scroll down and see 
],
 "coastal helicopter": [
  71
 ],
 "coastal helicopters": [
  71
 ],
 "Coastal Helicopter": [
  71
 ],
 "Coastal Helicopters": [
  71
 ],

Ok, I am by no way a programmer but I'm trying to learn and I see that we have 4 entries lower case/upper case/single/multiple. 

I go to missing.json and scroll thru the script and see, 

 ],
 "coastal helicopter": [
  71
 ],
 "coastal helicopters": [
  71
 ],
 "Coastal Helicopter": [
  71
 ],
 "Coastal Helicopters": [
  71
 ],

Hmm don't get it seems to me like it is there? What am I missing? 

I look at vehiclestats.json

I see the id 71 and the caption Coastal Helicopter. now I don't know if it needs to included lower case needs to have one with an (s) on the end. 

So, I'm not sure where to go from here or how to fix it. 

Thank you 

Mike

**Comment by NotoriousBims** [comment]
There are multiple entries for items like "coast helicopter" or "Coastal Helicopter" because of their lower/upper case needs and if they are plural or not. 

The vehicles arent required to be in the vehiclestats.json file although I will update them shortly.

**Comment by jackbayliss** [comment]
There shouldn't be a need for uppercase AND lowercase,  the bot casts everything to lowercase. If you have Discord I have a testing version that should fix the `educated personnel` issues.

**Comment by mlande5** [comment]
You can use ***@***.***
Thank you
Mike 
    On Monday, August 1, 2022 at 03:16:14 AM PDT, Jack ***@***.***> wrote:  
 
 


If you have discord or email, reach out to me- I have a new .exe for testing
