### ISSUE TITLE
Hire staff with the "automatically" button for stations

### ISSUE THREAD

**Issue by NotoriousBims** [jackbayliss/Mission-Chief-Bot#86]
Update the "hire staff" function to be able to select the "Automatically" button when hiring staff for stations. Note - this "automatically" button can only be used when the user is a premium member in-game.

**Comment by Tangiers2020** [comment]
Is there anyway of speeding the bot up for hiring staff?
As it can take some time to go through the stations?

**Comment by jackbayliss** [comment]
Yes On 12 Aug 2022 20:12, Hobbsie ***@***.***> wrote:
Is there anyway of speeding the bot up for hiring staff?
As it can take some time to go through the stations?

**Comment by jackbayliss** [comment]
> Is there anyway of speeding the bot up for hiring staff? As it can take some time to go through the stations?

Yes, I'll look at speeding it up

**Comment by jackbayliss** [comment]
Already done, simply set `hire_staff_days` to `automatic`

Will look at increasing speed.
