### ISSUE TITLE
No available hospitals.

### ISSUE THREAD

**Issue by Kulifloerkus** [jackbayliss/Mission-Chief-Bot#9]
I guess you don't load all the hospitals? When the first page is full, you have to press the following button to load all:
`<a href="/vehicles/123456789?load_all=true" class="btn btn-default">↓</a>`
![grafik](https://user-images.githubusercontent.com/64958878/82129797-bf2d7400-97c5-11ea-8d34-944b5632c0a8.png)

**Comment by jackbayliss** [comment]
@Kulifloerkus  I will implement this in the new patch, usually it will say no available hospitals if it's unable to find a green button.
