### ISSUE TITLE
Stripe does not Support Apple and GPay in Germany it seems

### ISSUE THREAD

**Issue by Harlekin7** [jackbayliss/Mission-Chief-Bot#92]
Currently, it is just Stripe which accepts the majority of cards as well as apple and gpay. I will look into paysafe and paypal perhaps.
If you want to pay via Apple pay you need to use safari on the iphone etc, and Gpay should work if enabled through the browser.

_Originally posted by @jackbayliss in https://github.com/jackbayliss/Mission-Chief-Bot/discussions/91#discussioncomment-3508667_

I literally tried everything to make Gpay Work on mobile and in Browser... Its working on any other payment website, but it seems your stripe checkout just doesnt show it...
Maybe there is something wrong on your side...
I tried making another Payment Account with Location in UK but its still not showing...
Only 4 kinds of Credit Card seem to be supported, but only few people actually use a Credit Card in Germany.

**Comment by jackbayliss** [comment]
@Harlekin7  I will look into it :)

**Comment by Harlekin7** [comment]
The Problem could be, that GPay in this Case only works as a way to fill out the Credit Card Info...
But i cant test it since i only got my Paypal as a Payment Method in Gpay

**Comment by jackbayliss** [comment]
@Harlekin7  I've enabled everything possible for payments, hopefully there's something you can use. Do you know why Gpay declined?

**Comment by Harlekin7** [comment]
No idea why Gpay Declined, but it works now
