### ISSUE TITLE
Website Bug - Edit User

### ISSUE THREAD

**Issue by Harlekin7** [jackbayliss/Mission-Chief-Bot#93]
Hey,
I have a 1 Account subscription...

Pressing the "Add User" Button does not work for me...
I tried on Chrome/Edge and Windows/Android

Thanks :)

**Comment by jackbayliss** [comment]
Try again nowOn 6 Sept 2022 07:42, Harlekin7 ***@***.***> wrote:
Hey,
I have a 1 Account subscription...
Pressing the "Add User" Button does not work for me...
I tried on Chrome/Edge and Windows/Android
Thanks :)

**Comment by Harlekin7** [comment]
Works 
Thank you
